services:
  dbx-components-offline-server:
    image: nginx:1.27
    ports:
      - '80'
      - '443:443'
    volumes:
      - type: bind
        source: ./docker/nginx/certs
        target: /etc/nginx/certs
        read_only: true
      - type: bind
        source: ./docker/nginx/snippets
        target: /etc/nginx/snippets
        read_only: true
      - type: bind
        source: ./docker/nginx/offline-nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./docker/nginx/html
        target: /usr/share/nginx/html
        read_only: true
      - type: bind
        source: ./tmp/nginx/webhook/nginx
        target: /var/log/nginx
