// THIS FILE IS GENERATED by scripts/extract-firebase-models.mjs.
// Do not edit by hand. Run `npx nx generate-firebase-models dbx-components-mcp`.

import type { FirebaseModel } from './firebase-models.js';

export const FIREBASE_MODELS: readonly FirebaseModel[] = [
  {
    name: 'NotificationBox',
    identityConst: 'notificationBoxIdentity',
    modelType: 'notificationBox',
    collectionPrefix: 'nb',
    sourceFile: 'packages/firebase/src/lib/model/notification/notification.ts',
    fields: [
      {
        name: 'cat',
        converter: 'firestoreDate()',
        tsType: 'Date',
        optional: false,
        description: 'Creation date of this NotificationBox document.'
      },
      {
        name: 'm',
        converter: 'firestoreModelKeyString',
        tsType: 'FirestoreModelKey',
        optional: false,
        description: "Model key of the model this box is assigned to (e.g., `'project/abc123'`)."
      },
      {
        name: 'o',
        converter: 'firestoreModelKeyString',
        tsType: 'FirestoreModelKey',
        optional: false,
        description: 'Owner model key. Set to a dummy value on creation and populated during server-side initialization.'
      },
      {
        name: 'r',
        converter: 'firestoreObjectArray({ objectField: firestoreNotificationBoxRecipient })',
        tsType: 'NotificationBoxRecipient[]',
        optional: false,
        description: 'Embedded recipient entries. Each entry represents a user who can receive notifications from this box. Synced from the corresponding {@link NotificationUser} `bc` configs.'
      },
      {
        name: 'w',
        converter: 'firestoreNumber({ default: () => yearWeekCode(new Date()) })',
        tsType: 'YearWeekCode',
        optional: false,
        description: 'Year-week code of the latest {@link NotificationWeek} subcollection document.'
      },
      {
        name: 's',
        converter: 'optionalFirestoreBoolean({ dontStoreIf: false })',
        tsType: 'Maybe<NeedsSyncBoolean>',
        optional: true,
        description: 'Whether this box needs server-side sync/initialization with its source model. Cleared when `fi` is set true (flagged invalid).'
      },
      {
        name: 'fi',
        converter: 'optionalFirestoreBoolean({ dontStoreIf: false })',
        tsType: 'Maybe<SavedToFirestoreIfTrue>',
        optional: true,
        description: 'Flagged invalid — set when the box cannot be properly initialized (e.g., source model deleted). The server can be configured to either flag or auto-delete invalid boxes.'
      }
    ],
    enums: [],
    detectionHints: ['m', 'r', 'w']
  },
  {
    name: 'NotificationSummary',
    identityConst: 'notificationSummaryIdentity',
    modelType: 'notificationSummary',
    collectionPrefix: 'ns',
    sourceFile: 'packages/firebase/src/lib/model/notification/notification.ts',
    fields: [
      {
        name: 'cat',
        converter: 'firestoreDate()',
        tsType: 'Date',
        optional: false,
        description: 'Creation date of this summary document.'
      },
      {
        name: 'm',
        converter: 'firestoreModelKeyString',
        tsType: 'FirestoreModelKey',
        optional: false,
        description: "Model key of the model this summary represents (e.g., `'project/abc123'`)."
      },
      {
        name: 'o',
        converter: 'firestoreModelKeyString',
        tsType: 'FirestoreModelKey',
        optional: false,
        description: 'Owner model key. Set to a dummy value on creation and populated during server-side initialization.'
      },
      {
        name: 'n',
        converter: 'firestoreObjectArray({ objectField: firestoreNotificationItem })',
        tsType: 'NotificationItem[]',
        optional: false,
        description: 'Embedded notification items, sorted ascending by date (newest at end).'
      },
      {
        name: 'lat',
        converter: 'optionalFirestoreDate()',
        tsType: 'Maybe<Date>',
        optional: true,
        description: 'Timestamp of the most recently added notification item.'
      },
      {
        name: 'rat',
        converter: 'optionalFirestoreDate()',
        tsType: 'Maybe<Date>',
        optional: true,
        description: 'Timestamp of when the user last read this summary. Items with dates after this are considered unread.'
      },
      {
        name: 's',
        converter: 'optionalFirestoreBoolean({ dontStoreIf: false })',
        tsType: 'Maybe<NeedsSyncBoolean>',
        optional: true,
        description: 'Whether this summary needs server-side sync/initialization with its source model.'
      },
      {
        name: 'fi',
        converter: 'optionalFirestoreBoolean({ dontStoreIf: false })',
        optional: true
      }
    ],
    enums: [],
    detectionHints: ['m', 'n', 'lat', 'rat']
  },
  {
    name: 'NotificationUser',
    identityConst: 'notificationUserIdentity',
    modelType: 'notificationUser',
    collectionPrefix: 'nu',
    sourceFile: 'packages/firebase/src/lib/model/notification/notification.ts',
    fields: [
      {
        name: 'uid',
        converter: 'firestoreUID()',
        optional: false
      },
      {
        name: 'b',
        converter: 'firestoreModelIdArrayField',
        tsType: 'NotificationBoxId[]',
        optional: false,
        description: 'Notification box IDs this user is subscribed to. Managed by the server — not directly editable by clients.'
      },
      {
        name: 'x',
        converter: 'firestoreModelIdArrayField',
        tsType: 'NotificationBoxSendExclusionList',
        optional: false,
        description:
          "Box exclusion list. Entries cause the user to be excluded from receiving notifications from matching boxes. Supports prefix matching: excluding `ab_123` also excludes child boxes like `ab_123_cd_456`. Populated by server-side model logic (e.g., when a user loses access to a resource). Exclusions are synced to the corresponding `bc` configs, which then propagate to the NotificationBoxes. Non-matching entries (where the user isn't associated with a matching box) are automatically removed."
      },
      {
        name: 'dc',
        converter: 'firestoreNotificationUserDefaultNotificationBoxRecipientConfig',
        tsType: 'NotificationUserDefaultNotificationBoxRecipientConfig',
        optional: false,
        description: "Direct/default config. Used when a recipient is added ad-hoc (by uid) to a notification that isn't associated with any of their subscribed boxes. Acts as the fallback config when no per-box config (`bc`) matches."
      },
      {
        name: 'gc',
        converter: 'firestoreNotificationUserDefaultNotificationBoxRecipientConfig',
        tsType: 'NotificationUserDefaultNotificationBoxRecipientConfig',
        optional: false,
        description: 'Global config override. Overrides all other configs (both per-box `bc` and direct/default `dc`) at send time. Unlike `dc`/`bc`, changes to `gc` are NOT copied to other config fields — they apply as a final override during notification delivery.'
      },
      {
        name: 'bc',
        converter: 'firestoreObjectArray({ objectField: firestoreNotificationUserNotificationBoxRecipientConfig })',
        tsType: 'NotificationUserNotificationBoxRecipientConfig[]',
        optional: false,
        description: "Per-box recipient configurations. Each entry corresponds to one of the user's subscribed notification boxes. These configs are synced bidirectionally with the {@link NotificationBoxRecipient} entries on the corresponding {@link NotificationBox}."
      },
      {
        name: 'ns',
        converter: 'optionalFirestoreBoolean()',
        tsType: 'Maybe<NeedsSyncBoolean>',
        optional: true,
        description: 'Whether one or more configs need to be synced to their corresponding NotificationBox recipients.'
      }
    ],
    enums: [],
    detectionHints: ['b', 'x', 'dc', 'gc', 'bc', 'ns']
  },
  {
    name: 'OidcEntry',
    identityConst: 'oidcEntryIdentity',
    modelType: 'oidcEntry',
    collectionPrefix: 'oidc_e',
    sourceFile: 'packages/firebase/src/lib/model/oidcmodel/oidcmodel.ts',
    fields: [
      {
        name: 'type',
        converter: "firestoreString<OidcEntryType>({ default: 'unknown' })",
        tsType: 'OidcEntryType',
        optional: false,
        description: "The oidc-provider model type (e.g., 'Session', 'AccessToken', 'Client')."
      },
      {
        name: 'payload',
        converter: 'firestorePassThroughField()',
        tsType: 'JsonSerializableObject',
        optional: false,
        description: 'Serialized JSON of the full oidc-provider AdapterPayload. The payload structure varies by model type. Sensitive fields may be selectively encrypted (prefixed with `$`) when encryption is configured.'
      },
      {
        name: 'o',
        converter: 'optionalFirestoreString()',
        tsType: 'Maybe<FirebaseAuthOwnershipKey>',
        optional: true,
        description: 'Ownership key for Firestore security rules. Set to the Firebase Auth UID of the user who created this entry. Used primarily on Client entries to allow users to query their own OAuth clients.'
      },
      {
        name: 'uid',
        converter: 'optionalFirestoreString()',
        tsType: 'Maybe<FirebaseAuthUserId>',
        optional: true,
        description: 'User identifier. Extracted from the payload for indexed queries.'
      },
      {
        name: 'grantId',
        converter: 'optionalFirestoreString()',
        tsType: 'Maybe<string>',
        optional: true,
        description: 'Grant identifier for revocation support. Extracted from the payload for indexed queries.'
      },
      {
        name: 'userCode',
        converter: 'optionalFirestoreString()',
        tsType: 'Maybe<string>',
        optional: true,
        description: 'User code for device flow. Extracted from the payload for indexed queries.'
      },
      {
        name: 'consumed',
        converter: 'optionalFirestoreNumber()',
        tsType: 'Maybe<number>',
        optional: true,
        description: 'Epoch timestamp when this entry was consumed. Extracted from the payload for indexed queries.'
      },
      {
        name: 'expiresAt',
        converter: 'optionalFirestoreDate()',
        tsType: 'Maybe<Date>',
        optional: true,
        description: 'When this entry expires.'
      }
    ],
    enums: [],
    detectionHints: ['type', 'payload', 'grantId', 'userCode', 'consumed', 'expiresAt']
  },
  {
    name: 'StorageFile',
    identityConst: 'storageFileIdentity',
    modelType: 'storageFile',
    collectionPrefix: 'sf',
    sourceFile: 'packages/firebase/src/lib/model/storagefile/storagefile.ts',
    fields: [
      {
        name: 'bucketId',
        converter: 'firestoreString()',
        optional: false
      },
      {
        name: 'pathString',
        converter: 'firestoreString()',
        optional: false
      },
      {
        name: 'n',
        converter: 'optionalFirestoreString()',
        tsType: 'Maybe<StorageFileDisplayName>',
        optional: true,
        description: "Arbitrary display name for the file. This name is used in StorageFileGroup composite file generations, instead of the file's normal path file name, if available."
      },
      {
        name: 'cat',
        converter: 'firestoreDate()',
        tsType: 'Date',
        optional: false,
        description: 'Created at date.'
      },
      {
        name: 'ct',
        converter: 'optionalFirestoreEnum<StorageFileCreationType>({ defaultReadValue: StorageFileCreationType.NONE, dontStoreDefaultReadValue: true })',
        tsType: 'Maybe<StorageFileCreationType>',
        optional: true,
        description: 'Type of creation.',
        enumRef: 'StorageFileCreationType'
      },
      {
        name: 'fs',
        converter: 'firestoreEnum<StorageFileState>({ default: StorageFileState.INIT })',
        tsType: 'StorageFileState',
        optional: false,
        description: 'State of the storage file.',
        enumRef: 'StorageFileState'
      },
      {
        name: 'ps',
        converter: 'firestoreEnum<StorageFileProcessingState>({ default: StorageFileProcessingState.INIT_OR_NONE })',
        tsType: 'StorageFileProcessingState',
        optional: false,
        description: 'Processing state of the storage file. The state is important for managing the processing of the StorageFile. Once processing is finished, the state determines whether or not the StorageFile can be processed again.',
        enumRef: 'StorageFileProcessingState'
      },
      {
        name: 'pn',
        converter: 'optionalFirestoreString()',
        tsType: 'Maybe<NotificationKey>',
        optional: true,
        description: 'The NotificationTask key for this storage file. Set only if the StorageFile has an associated NotificationTask. Cleared once the processing stage is no longer PROCESSING.'
      },
      {
        name: 'pat',
        converter: 'optionalFirestoreDate()',
        tsType: 'Maybe<Date>',
        optional: true,
        description: 'The date that state was last updated to PROCESSING. Is used as a way to track if processing should be checked on.'
      },
      {
        name: 'pcat',
        converter: 'optionalFirestoreDate()',
        tsType: 'Maybe<Date>',
        optional: true,
        description: 'The date that the cleanup step of the processing task was run, and the notification ended.'
      },
      {
        name: 'u',
        converter: 'optionalFirestoreString()',
        tsType: 'Maybe<FirebaseAuthUserId>',
        optional: true,
        description: 'User this file is associated with, if applicable.'
      },
      {
        name: 'uby',
        converter: 'optionalFirestoreString()',
        tsType: 'Maybe<FirebaseAuthUserId>',
        optional: true,
        description: 'User who uploaded this file, if applicable.'
      },
      {
        name: 'o',
        converter: 'optionalFirestoreString()',
        tsType: 'Maybe<FirebaseAuthOwnershipKey>',
        optional: true,
        description: 'Ownership key, if applicable.'
      },
      {
        name: 'p',
        converter: 'optionalFirestoreString()',
        tsType: 'Maybe<StorageFilePurpose>',
        optional: true,
        description: 'Purpose of the file, if applicable. Is required for processing a StorageFile.'
      },
      {
        name: 'pg',
        converter: 'optionalFirestoreString()',
        tsType: 'Maybe<StorageFilePurposeSubgroup>',
        optional: true,
        description: 'Subgroup of the purpose of the file, if applicable. If a StorageFilePurpose should have subgroups, then all StorageFiles should have subgroups too.'
      },
      {
        name: 'd',
        converter: 'firestorePassThroughField()',
        tsType: 'Maybe<M>',
        optional: true,
        description: 'Arbitrary metadata attached to the StorageFile.'
      },
      {
        name: 'sdat',
        converter: 'optionalFirestoreDate()',
        tsType: 'Maybe<Date>',
        optional: true,
        description: 'Scheduled delete at date. The StorageFile cannot be deleted before this set time. Is the main trigger for determining a StorageFile should be deleted.'
      },
      {
        name: 'g',
        converter: 'firestoreUniqueStringArray()',
        tsType: 'StorageFileGroupId[]',
        optional: false,
        description:
          'StorageFileGroup id(s) that this StorageFile should be associated with. These StorageFileGroup do not need to exist, and will be created when synchronization occurs. These groups by design should typically be pre-determined at the time the StorageFile is created and remain unchanged; timely removal of data from groups is not part of the design spec. When a StorageFile is updated to remove groups, the removal is eventually propogated to the StorageFileGroup(s) that it was associated with, but there is no gurantee about timeliness when this will happen. StorageFiles, when deleted, are removed from StorageFileGroups immediately, which are flagged for another regeneration automatically. In cases where you need to have the StorageFileGroup be updated promptly, you should manually handle those cases.'
      },
      {
        name: 'gs',
        converter: 'optionalFirestoreBoolean({ dontStoreIf: false })',
        tsType: 'Maybe<NeedsSyncBoolean>',
        optional: true,
        description: 'If true, this file should be re-synced with each StorageFileGroup that it references.'
      }
    ],
    enums: [
      {
        name: 'StorageFileCreationType',
        values: [
          {
            name: 'NONE',
            value: 0,
            description: 'No info about how this file was created.'
          },
          {
            name: 'DIRECTLY_CREATED',
            value: 1,
            description: 'The StorageFile was directly created.'
          },
          {
            name: 'INIT_FROM_UPLOAD',
            value: 2,
            description: 'The StorageFile was initialized from an uploaded file.'
          },
          {
            name: 'FOR_STORAGE_FILE_GROUP',
            value: 3,
            description: "This StorageFile was created by/for a StorageFileGroup. When creating a StorageFile via createStorageFileDocumentPairFactory(), this flag changes the behavior to use a parent StorageFileGroup to derive the created StorageFile's identifier."
          }
        ],
        description: 'How a StorageFile was created, which affects document ID generation and initialization behavior. When {@link FOR_STORAGE_FILE_GROUP} is used, the StorageFile ID is derived deterministically from the parent StorageFileGroup, enabling predictable document references.'
      },
      {
        name: 'StorageFileState',
        values: [
          {
            name: 'INIT',
            value: 0,
            description: 'The StorageFile has no state, or is just being initialized.'
          },
          {
            name: 'INVALID',
            value: 1,
            description: 'The StorageFile failed to initialize properly and is considered invalid. StorageFiles that are marked invalid are deleted after a period of time. Files that are invalid cannot be processed.'
          },
          {
            name: 'OK',
            value: 2,
            description: 'The StorageFile has been initialized and is ok.'
          },
          {
            name: 'QUEUED_FOR_DELETE',
            value: 3,
            description: 'A previously OK file that is now queued for deletion.'
          }
        ],
        description: 'Lifecycle state of a StorageFile document. State transitions: - `INIT` → `OK` (successful initialization) or `INVALID` (failed initialization) - `OK` → `QUEUED_FOR_DELETE` (flagged for deletion) - `INVALID` → (deleted after a period) - `QUEUED_FOR_DELETE` → (deleted once `sdat` is reached)'
      },
      {
        name: 'StorageFileProcessingState',
        values: [
          {
            name: 'INIT_OR_NONE',
            value: 0,
            description: 'The StorageFile has no processing state or is just being initialized.'
          },
          {
            name: 'QUEUED_FOR_PROCESSING',
            value: 1,
            description: 'The StorageFile is flagged for processing, which will create a NotificationTask for it.'
          },
          {
            name: 'PROCESSING',
            value: 2,
            description: 'The StorageFile has an associated NotificationTask for it.'
          },
          {
            name: 'FAILED',
            value: 3,
            description: 'The StorageFile has encountered an error during processing. It can be queued for reprocessing.'
          },
          {
            name: 'SUCCESS',
            value: 4,
            description: 'The StorageFile has been processed or required no processing and is done. It can be queued for reprocessing.'
          },
          {
            name: 'ARCHIVED',
            value: 5,
            description: 'The StorageFile has been archived. It cannot be queued for reprocessing.'
          },
          {
            name: 'DO_NOT_PROCESS',
            value: 6,
            description: "The StorageFile shouldn't be processed. It cannot be queued for reprocessing."
          }
        ],
        description:
          'Processing lifecycle state for a StorageFile. Processing is driven by NotificationTask integration. State transitions: - `INIT_OR_NONE` → `QUEUED_FOR_PROCESSING` (flagged for processing) - `QUEUED_FOR_PROCESSING` → `PROCESSING` (NotificationTask created) - `PROCESSING` → `SUCCESS` or `FAILED` - `FAILED` → `QUEUED_FOR_PROCESSING` (retry) or `DO_NOT_PROCESS` - `SUCCESS` → `QUEUED_FOR_PROCESSING` (reprocess) or `ARCHIVED` - `ARCHIVED` and `DO_NOT_PROCESS` are terminal states. Use {@link canQueueStorageFileForProcessing} to check if a file can be re-queued.'
      }
    ],
    detectionHints: ['bucketId', 'pathString', 'n', 'ct', 'fs', 'ps', 'pn', 'pat', 'pcat', 'uby', 'p', 'pg', 'sdat', 'g', 'gs']
  },
  {
    name: 'StorageFileGroup',
    identityConst: 'storageFileGroupIdentity',
    modelType: 'storageFileGroup',
    collectionPrefix: 'sfg',
    sourceFile: 'packages/firebase/src/lib/model/storagefile/storagefile.ts',
    fields: [
      {
        name: 'f',
        converter: 'firestoreObjectArray({ objectField: storageFileGroupEmbeddedFile })',
        tsType: 'StorageFileGroupEmbeddedFile[]',
        optional: false,
        description: 'List of embedded files in this group currently.'
      },
      {
        name: 'cat',
        converter: 'firestoreDate()',
        tsType: 'Date',
        optional: false,
        description: 'Created at date.'
      },
      {
        name: 'o',
        converter: 'optionalFirestoreString()',
        tsType: 'Maybe<FirebaseAuthOwnershipKey>',
        optional: true,
        description: 'Ownership key, if applicable.'
      },
      {
        name: 'z',
        converter: 'optionalFirestoreBoolean({ dontStoreIf: false })',
        tsType: 'Maybe<SavedToFirestoreIfTrue>',
        optional: true,
        description: 'True if a zip file should be generated for this group. This should remain true while a zip file'
      },
      {
        name: 'zsf',
        converter: 'optionalFirestoreString()',
        tsType: 'Maybe<StorageFileId>',
        optional: true,
        description: 'StorageFile that contains the zip file for this group.'
      },
      {
        name: 'zat',
        converter: 'optionalFirestoreDate()',
        tsType: 'Maybe<Date>',
        optional: true,
        description: 'The last date the zip file was regenerated for this group.'
      },
      {
        name: 's',
        converter: 'optionalFirestoreBoolean({ dontStoreIf: false })',
        optional: true
      },
      {
        name: 'fi',
        converter: 'optionalFirestoreBoolean({ dontStoreIf: false })',
        optional: true
      },
      {
        name: 're',
        converter: 'optionalFirestoreBoolean({ dontStoreIf: false })',
        tsType: 'Maybe<SavedToFirestoreIfTrue>',
        optional: true,
        description: 'True if this StorageFileGroup should flag regeneration of output StorageFiles/content.'
      },
      {
        name: 'c',
        converter: 'optionalFirestoreBoolean({ dontStoreIf: false })',
        tsType: 'Maybe<SavedToFirestoreIfTrue>',
        optional: true,
        description: 'True if this StorageFileGroup should clean up file references. This cleanup process will occur during the next regeneration.'
      }
    ],
    enums: [],
    detectionHints: ['f', 'z', 'zsf', 'zat', 're', 'c']
  },
  {
    name: 'SystemState',
    identityConst: 'systemStateIdentity',
    modelType: 'systemState',
    collectionPrefix: 'sys',
    sourceFile: 'packages/firebase/src/lib/model/system/system.ts',
    fields: [
      {
        name: 'data',
        converter: 'firestorePassThroughField()',
        tsType: 'T',
        optional: false
      }
    ],
    enums: [],
    detectionHints: ['data']
  },
  {
    name: 'Notification',
    identityConst: 'notificationIdentity',
    modelType: 'notification',
    collectionPrefix: 'nbn',
    sourceFile: 'packages/firebase/src/lib/model/notification/notification.ts',
    fields: [
      {
        name: 'cat',
        converter: 'firestoreDate({ saveDefaultAsNow: true })',
        tsType: 'Date',
        optional: false,
        description: 'Creation timestamp.'
      },
      {
        name: 'st',
        converter: 'firestoreEnum<NotificationSendType>({ default: NotificationSendType.SEND_IF_BOX_EXISTS })',
        tsType: 'NotificationSendType',
        optional: false,
        description: 'Send type controlling how this notification interacts with its parent NotificationBox.',
        enumRef: 'NotificationSendType'
      },
      {
        name: 'rf',
        converter: 'optionalFirestoreEnum<NotificationRecipientSendFlag>()',
        optional: true,
        enumRef: 'NotificationRecipientSendFlag'
      },
      {
        name: 'ts',
        converter: 'firestoreEnum<NotificationSendState>({ default: NotificationSendState.NONE })',
        optional: false,
        enumRef: 'NotificationSendState'
      },
      {
        name: 'es',
        converter: 'firestoreEnum<NotificationSendState>({ default: NotificationSendState.NONE })',
        optional: false,
        enumRef: 'NotificationSendState'
      },
      {
        name: 'ps',
        converter: 'firestoreEnum<NotificationSendState>({ default: NotificationSendState.NONE })',
        optional: false,
        enumRef: 'NotificationSendState'
      },
      {
        name: 'ns',
        converter: 'firestoreEnum<NotificationSendState>({ default: NotificationSendState.NONE })',
        optional: false,
        enumRef: 'NotificationSendState'
      },
      {
        name: 'n',
        converter: 'firestoreNotificationItem',
        tsType: 'NotificationItem',
        optional: false,
        description: 'Embedded notification content (subject, message, template type, metadata).'
      },
      {
        name: 'r',
        converter: 'firestoreObjectArray({ objectField: firestoreNotificationRecipientWithConfig })',
        tsType: 'NotificationRecipientWithConfig[]',
        optional: false,
        description: "Additional per-notification recipients with inline config overrides. Any `NotificationBoxRecipientTemplateConfig` values on these recipients affect opt-in/opt-out resolution. For example, setting `st: true` opts a user into text/SMS for this notification's template type, unless overridden by the user's own {@link NotificationUser} config."
      },
      {
        name: 'ois',
        converter: 'optionalFirestoreBoolean({ dontStoreIf: false })',
        tsType: 'Maybe<SavedToFirestoreIfTrue>',
        optional: true,
        description: "Explicit opt-in send only. When true, only sends to users who have explicitly opted in for each channel. Overrides the system-level default for this notification's template type."
      },
      {
        name: 'ots',
        converter: 'optionalFirestoreBoolean({ dontStoreIf: true })',
        tsType: 'Maybe<SavedToFirestoreIfFalse>',
        optional: true,
        description: "Opt-in text/SMS override. When false, sends text/SMS to all users even if they haven't explicitly opted in (still respects explicit opt-outs). Overrides the system-level default for this notification's template type."
      },
      {
        name: 'sat',
        converter: 'firestoreDate()',
        tsType: 'Date',
        optional: false,
        description: 'Scheduled send time. The notification is guaranteed to be sent only after this time. Also serves as a lock mechanism: during active sending, `sat` is pushed forward by a few minutes and the attempt counter is incremented, preventing concurrent send attempts.'
      },
      {
        name: 'a',
        converter: 'firestoreNumber({ default: 0 })',
        tsType: 'number',
        optional: false,
        description: 'Total error attempt count. Incremented only when sending encounters an error (not on success).'
      },
      {
        name: 'at',
        converter: 'optionalFirestoreNumber({ dontStoreIf: 0 })',
        tsType: 'Maybe<number>',
        optional: true,
        description: 'Current task attempt count for the active checkpoint. Incremented on delay or failure responses. Reset to 0 when a checkpoint completes successfully or when a new checkpoint begins.'
      },
      {
        name: 'd',
        converter: 'firestoreBoolean({ default: false })',
        tsType: 'boolean',
        optional: false,
        description: 'Delivery complete flag. When true, content has been delivered and is ready to archive to {@link NotificationWeek}. For task-type notifications this is always false — tasks are deleted upon completion instead of archived.'
      },
      {
        name: 'tsr',
        converter: 'firestoreUniqueStringArray()',
        optional: false
      },
      {
        name: 'esr',
        converter: 'firestoreUniqueStringArray()',
        optional: false
      },
      {
        name: 'tpr',
        converter: 'firestoreUniqueStringArray()',
        optional: false
      },
      {
        name: 'ut',
        converter: 'optionalFirestoreBoolean({ dontStoreIf: false })',
        tsType: 'Maybe<SavedToFirestoreIfTrue>',
        optional: true,
        description: 'Unique task flag. Only used for task-type notifications. When true, the server re-reads the document and compares `cat` before committing a task step. If `cat` has changed (indicating the task was replaced), the step is abandoned silently. This prevents stale task executions when a unique task ID is reused.'
      }
    ],
    enums: [
      {
        name: 'NotificationSendType',
        values: [
          {
            name: 'SEND_IF_BOX_EXISTS',
            value: 0,
            description: 'Sends only if the NotificationBox exists. Does not create a NotificationBox for the model.'
          },
          {
            name: 'INIT_BOX_AND_SEND',
            value: 1,
            description: "Creates a NotificationBox if it doesn't exist, and then sends the Notification."
          },
          {
            name: 'SEND_WITHOUT_CREATING_BOX',
            value: 2,
            description: 'Sends the notification even if the NotificationBox does not exist.'
          },
          {
            name: 'TASK_NOTIFICATION',
            value: 3,
            description: 'A task notification. This is used with Task-type notifications.'
          }
        ],
        description: 'Controls how a {@link Notification} interacts with its parent {@link NotificationBox} during delivery. Determines whether the box must exist, should be created on demand, or can be bypassed entirely. Task-type notifications (`TASK_NOTIFICATION`) bypass the box system and run async workflows instead.'
      },
      {
        name: 'NotificationSendState',
        values: [
          {
            name: 'NONE',
            value: -1,
            description: 'Notification will not be sent.'
          },
          {
            name: 'QUEUED',
            value: 0,
            description: 'Notification is queued up.'
          },
          {
            name: 'SENT',
            value: 1,
            description: 'Notification has been sent/complete. Will still show as sent even if there were no messages/recipients to send for this medium.'
          },
          {
            name: 'SENT_PARTIAL',
            value: 2,
            description: 'Some of the notifications have been sent, but some failed.'
          },
          {
            name: 'SKIPPED',
            value: 3,
            description: "Notification has been skipped due to the box's settings."
          },
          {
            name: 'NO_TRY',
            value: 4,
            description: 'Notification is flagged as being skipped and should not be reattempetd'
          },
          {
            name: 'SEND_ERROR',
            value: 5,
            description: 'Notification encountered an error while sending and could not be sent.'
          },
          {
            name: 'BUILD_ERROR',
            value: 6,
            description: 'Notification encountered an error while building and could not be sent.'
          },
          {
            name: 'CONFIG_ERROR',
            value: 7,
            description: 'Notification encountered an error due to the system not being configured properly.'
          }
        ],
        description: 'Lifecycle state of a notification delivery channel (text, email, push, or summary). Each channel on a {@link Notification} tracks its own send state independently via {@link NotificationSendFlags}. State transitions: - `QUEUED` → `SENT` (success) | `SENT_PARTIAL` (partial success) | `SEND_ERROR` | `BUILD_ERROR` | `CONFIG_ERROR` - `QUEUED` → `SKIPPED` (box settings) | `NO_TRY` (permanently skipped) - `NONE` indicates the channel was never queued for this notification'
      },
      {
        name: 'NotificationRecipientSendFlag',
        values: [
          {
            name: 'NORMAL',
            value: 0,
            description: 'Will send to all recipients.'
          },
          {
            name: 'SKIP_NOTIFICATION_BOX_RECIPIENTS',
            value: 1,
            description: 'Will not send to any of the configured notification box recipients. Will only to the globally configured message recpients or the notification specified recipients.'
          },
          {
            name: 'SKIP_GLOBAL_RECIPIENTS',
            value: 2,
            description: 'Will not send to any of the globally configured message recpients. Will only send to the notification specified recipients or the notification box recipients.'
          },
          {
            name: 'ONLY_EXPLICIT_RECIPIENTS',
            value: 3,
            description: 'Will only sent to recipients that are configured in this notification. Will not send to globally configured message recipients or notification box recipients.'
          },
          {
            name: 'ONLY_GLOBAL_RECIPIENTS',
            value: 4,
            description: 'Will only sent to globally configured message recipients.'
          }
        ],
        description: 'Notification recipient send flags.'
      }
    ],
    detectionHints: ['st', 'rf', 'ts', 'es', 'ps', 'ns', 'n', 'r', 'ois', 'ots', 'sat', 'a', 'at', 'tsr', 'esr', 'tpr', 'ut'],
    parentIdentityConst: 'notificationBoxIdentity'
  },
  {
    name: 'NotificationWeek',
    identityConst: 'notificationWeekIdentity',
    modelType: 'notificationWeek',
    collectionPrefix: 'nbnw',
    sourceFile: 'packages/firebase/src/lib/model/notification/notification.ts',
    fields: [
      {
        name: 'w',
        converter: 'firestoreNumber({ default: UNKNOWN_YEAR_WEEK_CODE })',
        tsType: 'YearWeekCode',
        optional: false,
        description: 'Year-week code identifying this week. Matches the document ID.'
      },
      {
        name: 'n',
        converter: 'firestoreObjectArray({ objectField: firestoreNotificationItem })',
        tsType: 'NotificationItem[]',
        optional: false,
        description: 'Archived notification items delivered during this week.'
      }
    ],
    enums: [],
    detectionHints: ['w', 'n'],
    parentIdentityConst: 'notificationBoxIdentity'
  }
];
