import { createRequire } from 'node:module';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { type Maybe } from '@dereekb/util';

/**
 * The `@dereekb/*` package prefix the drift check compares. Only framework packages are checked —
 * a third-party range like `firebase: ^12.12.1` is deliberately out of scope.
 */
export const CLI_FRAMEWORK_PACKAGE_PREFIX = '@dereekb/';

/**
 * Matches a declared dependency range that pins ONE exact version (`13.42.0`), which is the only
 * shape a build stamp can be read off. A range (`^13.42.0`, `~13.42`, `*`, a workspace or file
 * specifier) is skipped rather than guessed at.
 */
const EXACT_VERSION_RANGE = /^\d+\.\d+\.\d+(?:-[\w.]+)?$/;

/**
 * The artifact `package.json` a built CLI ships beside its entry file.
 *
 * `@nx/esbuild` copies the project's `package.json` verbatim into the output directory, so its
 * exact-pinned `@dereekb/*` peer versions ARE the build stamp — the dependency tree the bundle was
 * compiled against — with no extra build-time codegen to keep in sync.
 */
export interface CliArtifactPackage {
  /**
   * Absolute path the stamp was read from, reported so an operator can see WHICH artifact is running.
   */
  readonly path: string;
  readonly name?: Maybe<string>;
  readonly version?: Maybe<string>;
  /**
   * Every exact-pinned `@dereekb/*` version the artifact declares, from `peerDependencies` and
   * `dependencies` combined.
   */
  readonly frameworkVersions: Readonly<Record<string, string>>;
}

/**
 * One framework package whose built-against version differs from the version resolved at run time.
 */
export interface CliFrameworkVersionDrift {
  readonly packageName: string;
  readonly builtAgainst: string;
  /**
   * The version resolved from `node_modules` now, or `undefined` when the package is not installed.
   */
  readonly resolved?: Maybe<string>;
}

/**
 * Why {@link inspectCliBuildDrift} could not compare anything. A report with a `reason` is `ok`: an
 * undetectable stamp is not evidence of drift.
 */
export type CliBuildDriftUndeterminedReason =
  | 'no-entry-path'
  | 'no-artifact-package'
  | 'no-framework-versions-declared'
  /**
   * The artifact declares framework versions but NOT ONE of them resolves from `node_modules` — the
   * signature of running from SOURCE through a workspace's tsconfig paths (a monorepo dev run), where
   * there is no installed framework to drift from. Reporting every package as "not installed" here
   * would make the check red on every dev run, and a check that is red by default gets ignored.
   */
  | 'framework-not-resolvable';

/**
 * The verdict on whether the running artifact matches the dependency tree it was built against.
 */
export interface CliBuildDriftReport {
  readonly ok: boolean;
  readonly reason?: Maybe<CliBuildDriftUndeterminedReason>;
  readonly artifactPackagePath?: Maybe<string>;
  readonly artifactVersion?: Maybe<string>;
  /**
   * How many framework packages were actually comparable.
   */
  readonly checked: number;
  readonly drift: readonly CliFrameworkVersionDrift[];
  /**
   * The `@dereekb/dbx-cli` version that emitted the CLI's generated manifests, when the app passed
   * one through.
   */
  readonly manifestGeneratorVersion?: Maybe<string>;
  /**
   * The `@dereekb/dbx-cli` version resolved at run time.
   */
  readonly resolvedDbxCliVersion?: Maybe<string>;
  /**
   * True when the manifests were generated by a DIFFERENT `@dereekb/dbx-cli` than the one now
   * running them. This is the half the peer-version comparison cannot see: bumping the app's declared
   * peers without re-running the generators leaves the committed manifests behind, which is how a
   * manifest silently lost fields the runtime reads (`queryModesScanned: false` was this, unread).
   */
  readonly manifestGeneratorDrift: boolean;
}

/**
 * Input for {@link inspectCliBuildDrift}.
 */
export interface InspectCliBuildDriftInput {
  /**
   * The executed entry file. Defaults to `process.argv[1]`.
   */
  readonly entryPath?: Maybe<string>;
  /**
   * The generator version stamped into the app's generated manifests
   * (`<NAMESPACE>_STAMP.generatorVersion`), when the app wires one.
   */
  readonly manifestGeneratorVersion?: Maybe<string>;
  /**
   * Test seam: use this artifact stamp instead of discovering one from {@link entryPath}.
   */
  readonly artifactPackage?: Maybe<CliArtifactPackage>;
  /**
   * Test seam: resolves a package's installed version. Defaults to resolving each package's
   * `package.json` through `createRequire`.
   */
  readonly resolveVersion?: (packageName: string) => Maybe<string>;
}

/**
 * Compares the `@dereekb/*` versions the running artifact was BUILT against with the versions
 * resolved from `node_modules` now.
 *
 * This is the check whose absence turns a routine `@dereekb/*` bump into an unreadable runtime
 * failure. A CLI built with `thirdParty: false` inlines its app code and resolves the framework at
 * RUN time, so the artifact is only valid against the tree it was compiled against — and nothing
 * else in the toolchain notices when that stops being true. The symptom is arbitrary: an SDK
 * assertion, a missing manifest field, a silently-empty result.
 *
 * Deliberately conservative. Only exact-pinned `@dereekb/*` versions are compared, and every way the
 * comparison can fail to apply produces `ok: true` with a {@link CliBuildDriftUndeterminedReason} —
 * a check that cried wolf on every source-run CLI would be turned off, and then it would be useless
 * on the day it mattered.
 *
 * @param input - The entry path, the manifest generator stamp, and the test seams.
 * @returns The drift verdict.
 */
export function inspectCliBuildDrift(input: InspectCliBuildDriftInput = {}): CliBuildDriftReport {
  const { manifestGeneratorVersion } = input;
  const entryPath = input.entryPath ?? process.argv[1];
  const resolveVersion = input.resolveVersion ?? resolveInstalledPackageVersion;
  const artifactPackage = input.artifactPackage ?? (entryPath == null ? undefined : readCliArtifactPackage(entryPath));
  const resolvedDbxCliVersion = resolveVersion('@dereekb/dbx-cli');
  const manifestGeneratorDrift = manifestGeneratorVersion != null && resolvedDbxCliVersion != null && manifestGeneratorVersion !== resolvedDbxCliVersion;

  const declared = artifactPackage?.frameworkVersions ?? {};
  const drift: CliFrameworkVersionDrift[] = [];

  for (const [packageName, builtAgainst] of Object.entries(declared)) {
    const resolved = resolveVersion(packageName);

    if (resolved !== builtAgainst) {
      drift.push({ packageName, builtAgainst, ...(resolved == null ? {} : { resolved }) });
    }
  }

  const checked = Object.keys(declared).length;
  const noneResolvable = checked > 0 && drift.length === checked && drift.every((x) => x.resolved == null);
  let reason: Maybe<CliBuildDriftUndeterminedReason>;

  if (entryPath == null) {
    reason = 'no-entry-path';
  } else if (artifactPackage == null) {
    reason = 'no-artifact-package';
  } else if (checked === 0) {
    reason = 'no-framework-versions-declared';
  } else if (noneResolvable) {
    reason = 'framework-not-resolvable';
  }

  return {
    ok: (drift.length === 0 || noneResolvable) && !manifestGeneratorDrift,
    ...(reason == null ? {} : { reason }),
    ...(artifactPackage == null ? {} : { artifactPackagePath: artifactPackage.path, ...(artifactPackage.version == null ? {} : { artifactVersion: artifactPackage.version }) }),
    checked,
    drift,
    ...(manifestGeneratorVersion == null ? {} : { manifestGeneratorVersion }),
    ...(resolvedDbxCliVersion == null ? {} : { resolvedDbxCliVersion }),
    manifestGeneratorDrift
  };
}

/**
 * Renders a {@link CliBuildDriftReport} as one operator-facing line, for `--version` and for a
 * doctor suggestion.
 *
 * @param report - The report to describe.
 * @returns The description, or `undefined` when there is nothing to say.
 *
 * @__NO_SIDE_EFFECTS__
 */
export function cliBuildDriftDescription(report: CliBuildDriftReport): Maybe<string> {
  const parts: string[] = [];

  if (report.drift.length > 0 && report.reason !== 'framework-not-resolvable') {
    const builtAgainst = report.drift.map((x) => `${x.packageName}@${x.builtAgainst}`).join(', ');
    const installed = report.drift.map((x) => `${x.packageName}@${x.resolved ?? 'not installed'}`).join(', ');
    const verb = report.drift.length === 1 ? 'is' : 'are';

    parts.push(`built against ${builtAgainst} but ${installed} ${verb} installed`);
  }

  if (report.manifestGeneratorDrift) {
    parts.push(`generated manifests were emitted by @dereekb/dbx-cli@${report.manifestGeneratorVersion} but @dereekb/dbx-cli@${report.resolvedDbxCliVersion} is running them`);
  }

  return parts.length === 0 ? undefined : `STALE BUILD: this CLI was ${parts.join('; ')}. Rebuild it — a \`thirdParty: false\` artifact resolves @dereekb/* at run time, so a version bump alone does not update it.`;
}

/**
 * Finds and parses the artifact `package.json` nearest the executed entry file.
 *
 * @param entryPath - The executed entry file (`process.argv[1]`).
 * @returns The parsed stamp, or `undefined` when none could be read.
 */
export function readCliArtifactPackage(entryPath: string): Maybe<CliArtifactPackage> {
  const packageJsonPath = findNearestPackageJson(entryPath);
  let result: Maybe<CliArtifactPackage>;

  if (packageJsonPath != null) {
    try {
      const contents = JSON.parse(readFileSync(packageJsonPath, 'utf8')) as { readonly name?: unknown; readonly version?: unknown; readonly peerDependencies?: unknown; readonly dependencies?: unknown };

      result = {
        path: packageJsonPath,
        ...(typeof contents.name === 'string' ? { name: contents.name } : {}),
        ...(typeof contents.version === 'string' ? { version: contents.version } : {}),
        // peers first so a `dependencies` entry wins on a conflict: an app that pins a framework
        // package as a real dependency is the more specific declaration
        frameworkVersions: { ...exactFrameworkVersions(contents.peerDependencies), ...exactFrameworkVersions(contents.dependencies) }
      };
    } catch {
      // an unparsable or unreadable artifact package.json is indistinguishable from an absent one
      result = undefined;
    }
  }

  return result;
}

/**
 * The exact-pinned `@dereekb/*` entries of one dependency map.
 *
 * @param dependencies - A `package.json` dependency map, or any non-object value.
 * @returns Package name → exact version, for framework packages pinned to one version.
 */
function exactFrameworkVersions(dependencies: unknown): Record<string, string> {
  const result: Record<string, string> = {};

  if (dependencies != null && typeof dependencies === 'object') {
    for (const [packageName, range] of Object.entries(dependencies as Record<string, unknown>)) {
      if (packageName.startsWith(CLI_FRAMEWORK_PACKAGE_PREFIX) && typeof range === 'string' && EXACT_VERSION_RANGE.test(range)) {
        result[packageName] = range;
      }
    }
  }

  return result;
}

/**
 * Walks up from a file to the nearest directory holding a `package.json`.
 *
 * @param startPath - The file to start from.
 * @returns The `package.json` path, or `undefined` when the filesystem root is reached first.
 */
function findNearestPackageJson(startPath: string): Maybe<string> {
  let dir = dirname(resolve(startPath));
  let result: Maybe<string>;
  let searching = true;

  while (searching) {
    const candidate = resolve(dir, 'package.json');

    if (existsSync(candidate)) {
      result = candidate;
      searching = false;
    } else {
      const parent = dirname(dir);
      searching = parent !== dir;
      dir = parent;
    }
  }

  return result;
}

/**
 * Reads a package's installed version by resolving its `package.json` from THIS module's location —
 * the same resolution the CLI's own imports go through, so the answer is the version actually loaded.
 *
 * @param packageName - The package to resolve.
 * @returns The installed version, or `undefined` when it cannot be resolved.
 */
function resolveInstalledPackageVersion(packageName: string): Maybe<string> {
  let result: Maybe<string>;

  try {
    const contents = createRequire(import.meta.url)(`${packageName}/package.json`) as { readonly version?: unknown };
    result = typeof contents.version === 'string' ? contents.version : undefined;
  } catch {
    // a framework package the artifact declares but that is not installed shows up as drift with
    // `resolved: undefined`, which is the honest answer
    result = undefined;
  }

  return result;
}
