/**
 * Public surface of the rule-catalog runtime module.
 *
 * The catalog itself is generated by
 * `scripts/extract-rule-catalog.mjs` from the per-cluster
 * `codes.ts` enums and re-exported through
 * `generated/rule-catalog.generated.ts`. Consumers always import
 * from here (the runtime entry point) rather than reaching into
 * the generated file directly.
 */

export { RULE_CATALOG } from '../../../generated/rule-catalog.generated.js';
export { findRule, searchRules } from './find.js';
export { attachRemediation } from './attach-remediation.js';
export { formatRuleAsMarkdown, formatRuleAsJson } from './format.js';
export type { RuleEntry, RuleSeeAlso, RuleSeverity, RuleSource, RemediationHint } from './types.js';
