import { existsSync } from 'node:fs';
import * as path from 'node:path';
import { Module } from '@nestjs/common';
import { FirebaseServerEnvService } from '@dereekb/firebase-server';
import { McpModuleConfig, mcpModuleMetadata, MCP_AUTH_ROLE_READER, type McpAuthRoleReader } from '@dereekb/firebase-server/mcp';
import { OidcModuleConfig } from '@dereekb/firebase-server/oidc';
import { APP_CODE_PREFIX_CAPS_AUTH_CLAIMS_SERVICE } from 'FIREBASE_COMPONENTS_NAME';
import { APP_CODE_PREFIXApiOidcModule } from '../../api/oidc/oidc.module';
import { APP_CODE_PREFIXModelApiModule } from '../model/model.module';
import packageJson from '../../../../package.json';

const serverVersion: string = packageJson.version;

/**
 * Resolves the on-disk path to the build-time MCP manifest, generated by
 * `npx nx run API_APP_NAME:generate-mcp-manifest` at `dist/apps/API_APP_NAME/mcp.manifest.json`.
 *
 * The lookup copes with three `process.cwd()` values: the deployed function directory
 * (the Firebase Functions emulator + production runtime, where the manifest is colocated
 * with the bundle), the workspace root (dbx-cli), and the project root (vitest runs with
 * `cwd` set to `{projectRoot}`) — the last of which is why the workspace-root form is
 * probed against each ancestor directory rather than `cwd` alone.
 *
 * @param fileName - Manifest file name, e.g. `mcp.manifest.json`.
 * @returns The absolute path to the first candidate that exists, else the workspace-root form relative to `cwd` (so the loader logs a "missing file" warning naming that path).
 */
function resolveDistManifestPath(fileName: string): string {
  const cwd = process.cwd();
  const colocatedWithBundle = path.join(cwd, fileName);
  let result: string | undefined = existsSync(colocatedWithBundle) ? colocatedWithBundle : undefined;

  if (result == null) {
    let directory = cwd;

    for (;;) {
      const candidate = path.join(directory, 'dist/apps/API_APP_NAME', fileName);

      if (existsSync(candidate)) {
        result = candidate;
        break;
      }

      const parent = path.dirname(directory);

      if (parent === directory) {
        break;
      }

      directory = parent;
    }
  }

  return result ?? path.join(cwd, 'dist/apps/API_APP_NAME', fileName);
}

const MCP_MANIFEST_PATH = resolveDistManifestPath('mcp.manifest.json');

/**
 * Builds the MCP module config. `mcpUrl` comes from `envService.appMcpUrl` (else
 * `<api-origin>/mcp` derived from `appApiUrl`); `oidcIssuer` is sourced verbatim
 * from the resolved {@link OidcModuleConfig.issuer} so protected-resource
 * discovery always advertises the same issuer the OIDC provider uses.
 *
 * @param envService - Reads the app/API/MCP URLs.
 * @param oidcModuleConfig - The authoritative issuer source.
 * @returns The MCP module configuration aligned to the live origins.
 */
export function APP_CODE_PREFIX_CAMELMcpModuleConfigFactory(envService: FirebaseServerEnvService, oidcModuleConfig: OidcModuleConfig): McpModuleConfig {
  const apiBaseUrl = envService.appApiUrl ?? envService.appUrl;
  const apiOrigin = new URL(apiBaseUrl as string).origin;
  const mcpUrl = envService.appMcpUrl ?? `${apiOrigin}/mcp`;
  return {
    oidcIssuer: oidcModuleConfig.issuer,
    mcpUrl,
    serverName: 'API_APP_NAME-mcp',
    serverVersion,
    mcpManifestPath: MCP_MANIFEST_PATH
  };
}

/**
 * McpAuthRoleReader — maps a caller's Firebase custom claims through the app's
 * `authRoleClaimsService` to the AuthRoleSet the declarative MCP visibility rules consume.
 *
 * @param claims - The caller's Firebase custom claims to translate into roles.
 * @returns The AuthRoleSet derived from the claims.
 */
const APP_CODE_PREFIX_CAMELMcpAuthRoleReader: McpAuthRoleReader = (claims) => APP_CODE_PREFIX_CAPS_AUTH_CLAIMS_SERVICE.toRoles(claims);

/**
 * Dependency module for the MCP module: re-exports {@link APP_CODE_PREFIXModelApiModule}
 * (so its dispatch service reaches the MCP server factory) + the config provider, and
 * imports + re-exports {@link APP_CODE_PREFIXApiOidcModule} so {@link OidcModuleConfig} is
 * injectable here and its `OidcProviderConfigService` export propagates to the
 * `McpWellKnownController` (which reads the provider's `clientRequestableScopesSupported`).
 */
@Module({
  imports: [APP_CODE_PREFIXApiOidcModule, APP_CODE_PREFIXModelApiModule],
  providers: [
    {
      provide: McpModuleConfig,
      useFactory: APP_CODE_PREFIX_CAMELMcpModuleConfigFactory,
      inject: [FirebaseServerEnvService, OidcModuleConfig]
    },
    {
      provide: MCP_AUTH_ROLE_READER,
      useValue: APP_CODE_PREFIX_CAMELMcpAuthRoleReader
    }
  ],
  exports: [McpModuleConfig, MCP_AUTH_ROLE_READER, APP_CODE_PREFIXModelApiModule, APP_CODE_PREFIXApiOidcModule]
})
export class APP_CODE_PREFIXMcpDependencyModule {}

/**
 * Registers the MCP transport + protected-resource discovery controllers.
 *
 * Routes: `POST /mcp`, `GET /.well-known/oauth-protected-resource` (both excluded
 * from the global `/api` route prefix by the host config).
 */
@Module(
  mcpModuleMetadata({
    dependencyModule: APP_CODE_PREFIXMcpDependencyModule
  })
)
export class APP_CODE_PREFIXMcpModule {}
