import { existsSync } from 'node:fs';
import * as path from 'node:path';
import { Module } from '@nestjs/common';
import { FirebaseServerEnvService } from '@dereekb/firebase-server';
import { McpModuleConfig, mcpModuleMetadata, MCP_AUTH_ROLE_READER, type McpAuthRoleReader } from '@dereekb/firebase-server/mcp';
import { OidcModuleConfig } from '@dereekb/firebase-server/oidc';
import { APP_CODE_PREFIX_CAPS_AUTH_CLAIMS_SERVICE } from 'FIREBASE_COMPONENTS_NAME';
import { APP_CODE_PREFIXApiOidcModule } from '../../api/oidc/oidc.module';
import { APP_CODE_PREFIXModelApiModule } from '../model/model.module';
import packageJson from '../../../../package.json';

const serverVersion: string = packageJson.version;

/**
 * Resolves the on-disk path to the build-time MCP manifest, generated by
 * `npx nx run API_APP_NAME:generate-mcp-manifest` at `dist/apps/API_APP_NAME/mcp.manifest.json`.
 *
 * The lookup copes with two `process.cwd()` values: the workspace root (tests +
 * dbx-cli) and the deployed function directory (the Firebase Functions emulator +
 * production runtime, where the manifest is colocated with the bundle).
 *
 * @returns The absolute path to the MCP manifest, preferring the bundle-colocated file when present.
 */
function resolveMcpManifestPath(): string {
  const colocatedWithBundle = path.join(process.cwd(), 'mcp.manifest.json');
  const fromWorkspaceRoot = path.join(process.cwd(), 'dist/apps/API_APP_NAME/mcp.manifest.json');
  return existsSync(colocatedWithBundle) ? colocatedWithBundle : fromWorkspaceRoot;
}

const MCP_MANIFEST_PATH = resolveMcpManifestPath();

/**
 * Builds the MCP module config. `mcpUrl` comes from `envService.appMcpUrl` (else
 * `<api-origin>/mcp` derived from `appApiUrl`); `oidcIssuer` is sourced verbatim
 * from the resolved {@link OidcModuleConfig.issuer} so protected-resource
 * discovery always advertises the same issuer the OIDC provider uses.
 *
 * @param envService - Reads the app/API/MCP URLs.
 * @param oidcModuleConfig - The authoritative issuer source.
 * @returns The MCP module configuration aligned to the live origins.
 */
export function APP_CODE_PREFIX_CAMELMcpModuleConfigFactory(envService: FirebaseServerEnvService, oidcModuleConfig: OidcModuleConfig): McpModuleConfig {
  const apiBaseUrl = envService.appApiUrl ?? envService.appUrl;
  const apiOrigin = new URL(apiBaseUrl as string).origin;
  const mcpUrl = envService.appMcpUrl ?? `${apiOrigin}/mcp`;
  return {
    oidcIssuer: oidcModuleConfig.issuer,
    mcpUrl,
    serverName: 'API_APP_NAME-mcp',
    serverVersion,
    mcpManifestPath: MCP_MANIFEST_PATH
  };
}

/**
 * McpAuthRoleReader — maps a caller's Firebase custom claims through the app's
 * `authRoleClaimsService` to the AuthRoleSet the declarative MCP visibility rules consume.
 *
 * @param claims - The caller's Firebase custom claims to translate into roles.
 * @returns The AuthRoleSet derived from the claims.
 */
const APP_CODE_PREFIX_CAMELMcpAuthRoleReader: McpAuthRoleReader = (claims) => APP_CODE_PREFIX_CAPS_AUTH_CLAIMS_SERVICE.toRoles(claims);

/**
 * Dependency module for the MCP module: re-exports {@link APP_CODE_PREFIXModelApiModule}
 * (so its dispatch service reaches the MCP server factory) + the config provider, and
 * imports {@link APP_CODE_PREFIXApiOidcModule} so {@link OidcModuleConfig} is injectable.
 */
@Module({
  imports: [APP_CODE_PREFIXApiOidcModule, APP_CODE_PREFIXModelApiModule],
  providers: [
    {
      provide: McpModuleConfig,
      useFactory: APP_CODE_PREFIX_CAMELMcpModuleConfigFactory,
      inject: [FirebaseServerEnvService, OidcModuleConfig]
    },
    {
      provide: MCP_AUTH_ROLE_READER,
      useValue: APP_CODE_PREFIX_CAMELMcpAuthRoleReader
    }
  ],
  exports: [McpModuleConfig, MCP_AUTH_ROLE_READER, APP_CODE_PREFIXModelApiModule]
})
export class APP_CODE_PREFIXMcpDependencyModule {}

/**
 * Registers the MCP transport + protected-resource discovery controllers.
 *
 * Routes: `POST /mcp`, `GET /.well-known/oauth-protected-resource` (both excluded
 * from the global `/api` route prefix by the host config).
 */
@Module(
  mcpModuleMetadata({
    dependencyModule: APP_CODE_PREFIXMcpDependencyModule
  })
)
export class APP_CODE_PREFIXMcpModule {}
