import { existsSync } from 'node:fs';
import * as path from 'node:path';
import { Module } from '@nestjs/common';
import { FirebaseServerEnvService } from '@dereekb/firebase-server';
import { McpModuleConfig, mcpModuleMetadata, MCP_AUTH_ROLE_READER, type McpAuthRoleReader } from '@dereekb/firebase-server/mcp';
import { OidcModuleConfig } from '@dereekb/firebase-server/oidc';
import { DEMO_AUTH_CLAIMS_SERVICE } from 'demo-firebase';
import { DemoApiOidcModule } from '../../api/oidc/oidc.module';
import { DemoModelApiModule } from '../model/model.module';
import packageJson from '../../../../package.json';

const serverVersion: string = packageJson.version;

/**
 * Resolves the on-disk path to the build-time MCP manifest, which is generated by
 * `npx nx run demo-api:generate-mcp-manifest` and lands at
 * `dist/apps/demo-api/mcp.manifest.json`.
 *
 * The lookup has to cope with two different `process.cwd()` values:
 * - Tests + dbx-cli boot from the workspace root, so the manifest lives at
 *   `<cwd>/dist/apps/demo-api/mcp.manifest.json`.
 * - The Firebase Functions emulator + production runtime set `cwd` to the deployed
 *   function directory (the same one `main.js` was bundled into), so the manifest
 *   lives at `<cwd>/mcp.manifest.json` — sibling to the running bundle.
 *
 * Prior to this resolver the path was hardcoded to the workspace-root form, which
 * silently failed under the functions runtime and made the manifest-gated tools
 * (`model-info`, `model-decode`) invisible to MCP clients.
 *
 * @returns The absolute path to the MCP manifest, preferring the bundle-colocated file when it exists.
 */
function resolveMcpManifestPath(): string {
  const colocatedWithBundle = path.join(process.cwd(), 'mcp.manifest.json');
  const fromWorkspaceRoot = path.join(process.cwd(), 'dist/apps/demo-api/mcp.manifest.json');
  return existsSync(colocatedWithBundle) ? colocatedWithBundle : fromWorkspaceRoot;
}

const MCP_MANIFEST_PATH = resolveMcpManifestPath();

/**
 * Builds the MCP module config for the Demo API.
 *
 * `mcpUrl` is taken from `envService.appMcpUrl` when set; otherwise it falls back to
 * `<api-origin>/mcp` derived from `appApiUrl`. `oidcIssuer` is sourced verbatim from
 * the resolved {@link OidcModuleConfig.issuer} so the protected-resource discovery
 * doc always advertises the same issuer the OIDC provider itself uses — even when
 * the OIDC issuer is overridden via `oidcModuleMetadata` config.
 *
 * @param envService - The Firebase server environment service used to read app/API/MCP URLs.
 * @param oidcModuleConfig - The resolved OIDC module config, used as the authoritative issuer source.
 * @returns The MCP module configuration with discovery URLs aligned to the live origins.
 */
export function demoMcpModuleConfigFactory(envService: FirebaseServerEnvService, oidcModuleConfig: OidcModuleConfig): McpModuleConfig {
  const apiBaseUrl = envService.appApiUrl ?? envService.appUrl;
  const apiOrigin = new URL(apiBaseUrl as string).origin;
  const mcpUrl = envService.appMcpUrl ?? `${apiOrigin}/mcp`;
  return {
    oidcIssuer: oidcModuleConfig.issuer,
    mcpUrl,
    serverName: 'demo-api-mcp',
    serverVersion,
    serverInstructions: 'Demo API MCP tools for the dbx-components guestbook/profile sample models. Generated from the callModel _apiDetails tree.',
    mcpManifestPath: MCP_MANIFEST_PATH
  };
}

/**
 * McpAuthRoleReader implementation for the demo app — maps a caller's Firebase
 * custom claims through the demo's `authRoleClaimsService` to the AuthRoleSet
 * the declarative {@link McpVisibilityRule.requiredRoles} check consumes.
 *
 * @param claims - The caller's Firebase custom claims object to translate into roles.
 * @returns The AuthRoleSet derived from the claims, used by the MCP visibility check.
 */
const demoMcpAuthRoleReader: McpAuthRoleReader = (claims) => DEMO_AUTH_CLAIMS_SERVICE.toRoles(claims);

/**
 * Dependency module for the Demo MCP module.
 *
 * Re-exports {@link DemoModelApiModule} so its `ModelApiCallModelDispatchService`
 * export propagates to `McpServerFactoryService`, plus the MCP module config provider.
 * Imports {@link DemoApiOidcModule} so {@link OidcModuleConfig} is available to the
 * MCP config factory.
 */
@Module({
  imports: [DemoApiOidcModule, DemoModelApiModule],
  providers: [
    {
      provide: McpModuleConfig,
      useFactory: demoMcpModuleConfigFactory,
      inject: [FirebaseServerEnvService, OidcModuleConfig]
    },
    {
      provide: MCP_AUTH_ROLE_READER,
      useValue: demoMcpAuthRoleReader
    }
  ],
  exports: [McpModuleConfig, MCP_AUTH_ROLE_READER, DemoModelApiModule]
})
export class DemoMcpDependencyModule {}

/**
 * Registers the MCP transport + protected-resource discovery controllers for the demo app.
 *
 * Routes: `POST /mcp`, `GET /.well-known/oauth-protected-resource` (both excluded
 * from the global `/api` route prefix by the host config).
 */
@Module(
  mcpModuleMetadata({
    dependencyModule: DemoMcpDependencyModule
  })
)
export class DemoMcpModule {}
