import { type LabeledValue, type LabeledValueWithDescription } from '@dereekb/util';

/**
 * Unique identifier for an oidc-provider interaction session, not to be confused with a Firebase UID/Auth User Identifier.
 *
 * Generated by the provider when user interaction is needed (login/consent).
 * Used to look up the interaction session via cookies and to build
 * backend interaction endpoint URLs (e.g., `/interaction/${uid}/login`).
 *
 * @semanticType
 * @semanticTopic identifier
 * @semanticTopic string
 * @semanticTopic dereekb-firebase:oidc
 */
export type OidcInteractionUid = string;

/**
 * Base type for OIDC scope string unions.
 *
 * Applications define their own scope union extending this type to get
 * compile-time validation of scope names throughout the delegate and config.
 *
 * @example
 * ```typescript
 * type MyScopes = 'openid' | 'profile' | 'email';
 * ```
 *
 * @semanticType
 * @semanticTopic string
 * @semanticTopic dereekb-firebase:oidc
 */
export type OidcScope = string;

/**
 * Scope details with a human-readable label and description.
 */
export type OidcScopeDetails<T extends OidcScope = OidcScope> = LabeledValueWithDescription<T>;

/**
 * A redirect URI registered to an OIDC client.
 *
 * Must be a valid absolute URL (e.g. `https://myapp.example.com/callback`).
 *
 * @semanticType
 * @semanticTopic url
 * @semanticTopic string
 * @semanticTopic dereekb-firebase:oidc
 */
export type OidcRedirectUri = string;

/**
 * Supported values for `token_endpoint_auth_method` when creating an OIDC client.
 *
 * The four `client_secret_*` / `private_key_jwt` methods are for confidential clients.
 *
 * `'none'` designates a public client: it holds no secret and authenticates the
 * `authorization_code` flow with PKCE alone. This is the canonical pattern for clients
 * that cannot keep a secret (native apps, SPAs, CLIs) and is what the MCP / Claude
 * connector ecosystem (claude.ai connector, Claude Code CLI, mcp-inspector via DCR)
 * expects. oidc-provider enforces PKCE on the `authorization_code` flow for every
 * client regardless of auth method, so all clients get PKCE; `'none'` simply unlocks
 * the secret-less variant.
 */
export type OidcTokenEndpointAuthMethod = 'client_secret_basic' | 'client_secret_post' | 'client_secret_jwt' | 'private_key_jwt' | 'none';

export const PRIVATE_KEY_JWT_TOKEN_ENDPOINT_AUTH_METHOD: OidcTokenEndpointAuthMethod = 'private_key_jwt';

/**
 * The public-client auth method (`'none'`): no client secret, PKCE-only.
 *
 * Mirrors {@link PRIVATE_KEY_JWT_TOKEN_ENDPOINT_AUTH_METHOD}. Use this when provisioning
 * public OAuth clients that cannot keep a secret.
 */
export const PUBLIC_PKCE_TOKEN_ENDPOINT_AUTH_METHOD: OidcTokenEndpointAuthMethod = 'none';

/**
 * All available token endpoint auth method options with display labels.
 */
export const ALL_OIDC_TOKEN_ENDPOINT_AUTH_METHOD_OPTIONS: LabeledValue<OidcTokenEndpointAuthMethod>[] = [
  { label: 'Client Secret Basic', value: 'client_secret_basic' },
  { label: 'Client Secret Post', value: 'client_secret_post' },
  { label: 'Client Secret JWT', value: 'client_secret_jwt' },
  { label: 'Private Key JWT', value: PRIVATE_KEY_JWT_TOKEN_ENDPOINT_AUTH_METHOD },
  { label: 'None (Public PKCE)', value: PUBLIC_PKCE_TOKEN_ENDPOINT_AUTH_METHOD }
];

/**
 * All available OIDC token endpoint auth methods for the demo app, suitable for use in auth method picker fields.
 */
export const ALL_OIDC_TOKEN_ENDPOINT_AUTH_METHODS: OidcTokenEndpointAuthMethod[] = ALL_OIDC_TOKEN_ENDPOINT_AUTH_METHOD_OPTIONS.map((x) => x.value);
