import { type LabeledValue, type LabeledValueWithDescription } from '@dereekb/util';

/**
 * Unique identifier for an oidc-provider interaction session, not to be confused with a Firebase UID/Auth User Identifier.
 *
 * Generated by the provider when user interaction is needed (login/consent).
 * Used to look up the interaction session via cookies and to build
 * backend interaction endpoint URLs (e.g., `/interaction/${uid}/login`).
 */
export type OidcInteractionUid = string;

/**
 * Base type for OIDC scope string unions.
 *
 * Applications define their own scope union extending this type to get
 * compile-time validation of scope names throughout the delegate and config.
 *
 * @example
 * ```typescript
 * type MyScopes = 'openid' | 'profile' | 'email';
 * ```
 */
export type OidcScope = string;

/**
 * Scope details with a human-readable label and description.
 */
export type OidcScopeDetails<T extends OidcScope = OidcScope> = LabeledValueWithDescription<T>;

/**
 * A redirect URI registered to an OIDC client.
 *
 * Must be a valid absolute URL (e.g. `https://myapp.example.com/callback`).
 */
export type OidcRedirectUri = string;

/**
 * Supported values for `token_endpoint_auth_method` when creating an OIDC client.
 */
export type OidcTokenEndpointAuthMethod = 'client_secret_basic' | 'client_secret_post' | 'client_secret_jwt' | 'private_key_jwt';

export const PRIVATE_KEY_JWT_TOKEN_ENDPOINT_AUTH_METHOD: OidcTokenEndpointAuthMethod = 'private_key_jwt';

/**
 * All available token endpoint auth method options with display labels.
 */
export const ALL_OIDC_TOKEN_ENDPOINT_AUTH_METHOD_OPTIONS: LabeledValue<OidcTokenEndpointAuthMethod>[] = [
  { label: 'Client Secret Basic', value: 'client_secret_basic' },
  { label: 'Client Secret Post', value: 'client_secret_post' },
  { label: 'Client Secret JWT', value: 'client_secret_jwt' },
  { label: 'Private Key JWT', value: PRIVATE_KEY_JWT_TOKEN_ENDPOINT_AUTH_METHOD }
];
