import { type ContentTypeMimeType, type Maybe } from '@dereekb/util';
import { type TrelloAttachmentId, type TrelloMemberId } from '../trello.type';

/**
 * A scaled preview generated by Trello for image attachments.
 *
 * @see https://developer.atlassian.com/cloud/trello/rest/api-group-cards/#api-cards-id-attachments-id-get
 */
export interface TrelloAttachmentPreview {
  readonly id: string;
  readonly url: string;
  readonly bytes: number;
  readonly width: number;
  readonly height: number;
  readonly scaled: boolean;
}

/**
 * A Trello attachment.
 *
 * Attachments can be uploaded files or URL-only references. File attachments expose `bytes`, `mimeType`,
 * and a non-empty `previews` array for image content. URL attachments have `bytes === null` and an empty
 * `previews` array.
 *
 * @see https://developer.atlassian.com/cloud/trello/rest/api-group-cards/#api-cards-id-attachments-get
 */
export interface TrelloAttachment {
  readonly id: TrelloAttachmentId;
  readonly idMember: TrelloMemberId;
  readonly name: string;
  /**
   * Original file name (for uploaded files). Empty for URL-only attachments.
   */
  readonly fileName: string;
  /**
   * Authenticated download url for the attachment file (or the external url for URL-only attachments).
   *
   * For uploaded private files Trello requires the OAuth `Authorization` header to download.
   */
  readonly url: string;
  /**
   * File size in bytes, or `null` for URL-only attachments.
   */
  readonly bytes: Maybe<number>;
  /**
   * MIME type of the uploaded file, or `null` for URL-only attachments.
   */
  readonly mimeType: Maybe<ContentTypeMimeType>;
  readonly date: string;
  readonly edgeColor: Maybe<string>;
  readonly pos: number;
  readonly isUpload: boolean;
  readonly previews: ReadonlyArray<TrelloAttachmentPreview>;
}

export interface AddAttachmentToCardFileInput {
  /**
   * File bytes to upload. Accepts anything `BlobPart` supports — `Buffer`, `Uint8Array`, `ArrayBuffer`, `string`, or a `Blob`.
   */
  readonly content: BlobPart;
  /**
   * File name (including extension) that Trello will display.
   */
  readonly fileName: string;
  /**
   * MIME type for the uploaded file. Defaults to `application/octet-stream` when omitted.
   */
  readonly mimeType?: ContentTypeMimeType;
}

export interface AddAttachmentToCardBody {
  /**
   * Optional display name. Defaults to the file name (for file uploads) or the url (for url-only attachments).
   */
  readonly name?: string;
  /**
   * Uploads a file. Mutually exclusive with `url`.
   */
  readonly file?: AddAttachmentToCardFileInput;
  /**
   * Attaches an external url. Mutually exclusive with `file`.
   */
  readonly url?: string;
  /**
   * If true, asks Trello to use this attachment for the card cover (uploaded files only).
   */
  readonly setCover?: boolean;
  /**
   * Optional mimeType override sent as a form field — only honored for url-only attachments.
   */
  readonly mimeType?: ContentTypeMimeType;
}
