import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { toObservable, toSignal } from '@angular/core/rxjs-interop';
import { DbxActionButtonDirective, DbxActionDirective, DbxActionDisabledDirective, DbxActionHandlerDirective, DbxActionValueDirective } from '@dereekb/dbx-core';
import { type DbxActionConfirmConfig, DbxActionConfirmDirective, DbxActionSnackbarErrorDirective, DbxButtonComponent, DbxErrorComponent, DbxActionErrorDirective } from '@dereekb/dbx-web';
import { type WorkUsingContext } from '@dereekb/rxjs';
import { switchMap } from 'rxjs';
import { type CalendarDocumentStore } from '../store/calendar.document.store';

/**
 * Button that rotates a calendar's published ICS link, revoking the url subscribers currently hold.
 *
 * Its own component rather than markup inside the subscribe dialog because everything it has to express is
 * about the action and none of it is about the dialog: rotation needs a calendar that exists, the server
 * enforces a rotation throttle, and the confirm prompt has to spell out that every existing subscription
 * breaks. A caller that wants the affordance somewhere else — an admin screen, a settings page — drops in
 * the same component.
 *
 * Renders nothing but the button, unconditionally, and disables it instead of substituting an explanation —
 * so a host's layout does not shift with the calendar's state and the control stays exactly where the caller
 * put it. The disabled reason is deliberately unstated: the confirm prompt is where the consequences belong,
 * and the server rejects an early rotation regardless.
 */
@Component({
  selector: 'dbx-firebase-calendar-ics-rotate-button',
  template: `
    <!-- dbxActionDisabled rather than the button's own disabled input, since dbxActionButton drives that from the action's state -->
    <!-- the action takes no input, so the bare dbxActionValue marks it value-ready on trigger -->
    <div dbxAction dbxActionValue dbxActionSnackbarError [dbxActionDisabled]="isDisabledSignal()" [dbxActionHandler]="handleRotateLink" [dbxActionConfirm]="rotateConfirmConfig">
      <dbx-button dbxActionButton color="warn" icon="autorenew" text="Rotate Link"></dbx-button>
      <dbx-error dbxActionError></dbx-error>
    </div>
  `,
  host: { class: 'dbx-firebase-calendar-ics-rotate-button' },
  imports: [DbxActionDirective, DbxActionValueDirective, DbxActionDisabledDirective, DbxActionHandlerDirective, DbxActionButtonDirective, DbxActionConfirmDirective, DbxActionSnackbarErrorDirective, DbxActionErrorDirective, DbxButtonComponent, DbxErrorComponent],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class DbxFirebaseCalendarIcsRotateButtonComponent {
  /**
   * Store for the calendar whose link is rotated.
   *
   * An input rather than an injected store, since the most common host is a dialog that received its store
   * through `MAT_DIALOG_DATA` and therefore cannot provide it through the injector.
   */
  readonly calendarDocumentStore = input.required<CalendarDocumentStore>();

  readonly calendarDocumentStore$ = toObservable(this.calendarDocumentStore);

  /**
   * Whether the calendar document exists, which is the precondition for rotating its link.
   *
   * The callable authorizes against the Calendar itself, so a key that names nothing is rejected rather
   * than reported as a no-op revocation.
   */
  readonly existsSignal = toSignal(this.calendarDocumentStore$.pipe(switchMap((x) => x.exists$)), { initialValue: false });

  readonly isThrottledSignal = toSignal(this.calendarDocumentStore$.pipe(switchMap((x) => x.isIcsRotateThrottled$)), { initialValue: false });

  /**
   * Whether rotation is unavailable, for either of its two reasons.
   *
   * The button stays rendered and goes disabled rather than being swapped for an explanation, so the control
   * a caller lays out is in the same place whatever the calendar's state.
   */
  readonly isDisabledSignal = computed(() => {
    // both read unconditionally, so the computed tracks them on every run
    const exists = this.existsSignal();
    const isThrottled = this.isThrottledSignal();

    return !exists || isThrottled;
  });

  readonly rotateConfirmConfig: DbxActionConfirmConfig = {
    title: 'Rotate the calendar link?',
    prompt: 'The current link stops working and every calendar already subscribed to it breaks. A new link is generated by the next sync.',
    confirmText: 'Rotate Link'
  };

  readonly handleRotateLink: WorkUsingContext = (_, context) => {
    context.startWorkingWithLoadingStateObservable(this.calendarDocumentStore().rotateIcs({}));
  };
}
