import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { toObservable, toSignal } from '@angular/core/rxjs-interop';
import { DbxActionButtonDirective, DbxActionDirective, DbxActionDisabledDirective, DbxActionHandlerDirective, DbxActionValueDirective, TimeDistanceCountdownPipe } from '@dereekb/dbx-core';
import { type DbxActionConfirmConfig, DbxActionConfirmDirective, DbxActionSnackbarErrorDirective, DbxButtonComponent, DbxErrorComponent, DbxActionErrorDirective } from '@dereekb/dbx-web';
import { type WorkUsingContext } from '@dereekb/rxjs';
import { switchMap } from 'rxjs';
import { type CalendarDocumentStore } from '../store/calendar.document.store';

/**
 * Button that rotates a calendar's published ICS link, revoking the url subscribers currently hold.
 *
 * Its own component rather than markup inside the subscribe dialog because the three states it has to
 * express are all about the action and none are about the dialog: there is nothing to revoke before the
 * calendar exists, the server enforces a rotation throttle, and the confirm prompt has to spell out that
 * every existing subscription breaks. A caller that wants the affordance somewhere else — an admin screen,
 * a settings page — drops in the same component.
 */
@Component({
  selector: 'dbx-firebase-calendar-ics-rotate-button',
  template: `
    @if (existsSignal()) {
      <!-- dbxActionDisabled rather than the button's own disabled input, since dbxActionButton drives that from the action's state -->
      <!-- the action takes no input, so the bare dbxActionValue marks it value-ready on trigger -->
      <div dbxAction dbxActionValue dbxActionSnackbarError [dbxActionDisabled]="isThrottledSignal()" [dbxActionHandler]="handleRotateLink" [dbxActionConfirm]="rotateConfirmConfig">
        <dbx-button dbxActionButton icon="autorenew" text="Rotate Link"></dbx-button>
        <dbx-error dbxActionError></dbx-error>
      </div>
      @if (throttledUntilSignal(); as throttledUntil) {
        <div class="dbx-small dbx-hint dbx-pt2">This link was rotated recently. It can be rotated again {{ throttledUntil | timeCountdownDistance }}.</div>
      }
    } @else {
      <p class="dbx-hint">This calendar does not exist yet, so there is no link to revoke.</p>
    }
  `,
  host: { class: 'dbx-firebase-calendar-ics-rotate-button' },
  imports: [DbxActionDirective, DbxActionValueDirective, DbxActionDisabledDirective, DbxActionHandlerDirective, DbxActionButtonDirective, DbxActionConfirmDirective, DbxActionSnackbarErrorDirective, DbxActionErrorDirective, DbxButtonComponent, DbxErrorComponent, TimeDistanceCountdownPipe],
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class DbxFirebaseCalendarIcsRotateButtonComponent {
  /**
   * Store for the calendar whose link is rotated.
   *
   * An input rather than an injected store, since the most common host is a dialog that received its store
   * through `MAT_DIALOG_DATA` and therefore cannot provide it through the injector.
   */
  readonly calendarDocumentStore = input.required<CalendarDocumentStore>();

  readonly calendarDocumentStore$ = toObservable(this.calendarDocumentStore);

  /**
   * Whether the calendar document exists, which is the precondition for rotating its link.
   *
   * The callable authorizes against the Calendar itself, so a key that names nothing is rejected rather
   * than reported as a no-op revocation.
   */
  readonly existsSignal = toSignal(this.calendarDocumentStore$.pipe(switchMap((x) => x.exists$)), { initialValue: false });

  readonly isThrottledSignal = toSignal(this.calendarDocumentStore$.pipe(switchMap((x) => x.isIcsRotateThrottled$)), { initialValue: false });

  readonly nextIcsRotateAtSignal = toSignal(this.calendarDocumentStore$.pipe(switchMap((x) => x.nextIcsRotateAt$)));

  /**
   * The time the throttle lifts, or undefined when a rotation is allowed right now.
   *
   * Gated on the throttle rather than rendered from the date alone: `nextIcsRotateAt` stays populated once
   * the window has passed, and a hint counting down to a time already gone reads as a bug.
   */
  readonly throttledUntilSignal = computed(() => {
    // both read unconditionally, so the computed tracks them on every run
    const isThrottled = this.isThrottledSignal();
    const nextIcsRotateAt = this.nextIcsRotateAtSignal();

    return isThrottled ? nextIcsRotateAt : undefined;
  });

  readonly rotateConfirmConfig: DbxActionConfirmConfig = {
    title: 'Rotate the calendar link?',
    prompt: 'The current link stops working and every calendar already subscribed to it breaks. A new link is generated by the next sync.',
    confirmText: 'Rotate Link'
  };

  readonly handleRotateLink: WorkUsingContext = (_, context) => {
    context.startWorkingWithLoadingStateObservable(this.calendarDocumentStore().rotateIcs({}));
  };
}
