/* eslint-disable @nx/enforce-module-boundaries */
// AUTO-GENERATED — DO NOT EDIT.
// Run `npx nx run demo-cli:generate-firestore-query-manifest` to refresh.

import {
  calendarsDueForResyncQuery,
  calendarsFlaggedForSyncQuery,
  calendarsForTypeQuery,
  formSpacesDueForExpirationQuery,
  formSpacesForOwnerQuery,
  formSpacesQueuedForProcessingQuery,
  notificationBoxesFlaggedForNeedsInitializationQuery,
  notificationBoxesFlaggedInvalidQuery,
  notificationLoggedEventDaysOlderThanQuery,
  notificationsNewestFirstQuery,
  notificationsPastSendAtTimeQuery,
  notificationsReadyForCleanupQuery,
  notificationSummariesFlaggedForNeedsInitializationQuery,
  notificationUserHasExclusionQuery,
  notificationUsersFlaggedForNeedsSyncQuery,
  oidcClientEntriesByOwnerQuery,
  oidcEntriesByClientIdQuery,
  oidcEntriesByGrantIdQuery,
  oidcEntriesByUidQuery,
  oidcEntriesByUserCodeQuery,
  oidcEntriesWithTypeQuery,
  oidcGrantEntriesByUidQuery,
  storageFileFlaggedForSyncWithGroupsQuery,
  storageFileGroupsFlaggedForContentRegenerationQuery,
  storageFileGroupsFlaggedForNeedsInitializationQuery,
  storageFileGroupsFlaggedInvalidQuery,
  storageFilePurposeAndUserQuery,
  storageFilesForFormSpaceQuery,
  storageFilesQueuedForDeleteQuery,
  storageFilesQueuedForProcessingQuery,
  userExternalConnectionsWithConnectedProviderQuery,
  userExternalConnectionsWithExternalAccountQuery
} from '@dereekb/firebase';
import { openRouterPromptsWithStateQuery, openRouterRunTasksExpiredQuery, openRouterRunTasksReclaimableQuery, openRouterRunTasksRunnableQuery } from '@dereekb/openrouter/firebase';
import { profileWithUsernameQuery, publishedGuestbookEntriesQuery, publishedGuestbooksQuery } from 'demo-firebase';
import { type CliFirestoreQueryManifest, type CliGeneratedManifestStamp } from '@dereekb/dbx-cli';

export const DEMO_CLI_FIRESTORE_QUERY_MANIFEST_STAMP: CliGeneratedManifestStamp = { generatorVersion: '14.9.0' };

export const DEMO_CLI_FIRESTORE_QUERY_MANIFEST: CliFirestoreQueryManifest = [
  {
    slug: 'calendars-due-for-resync-query',
    name: 'calendarsDueForResyncQuery',
    module: '@dereekb/firebase',
    subpath: 'model/calendar/calendar.query',
    model: 'Calendar',
    collection: 'cal',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'calendarsDueForResyncQuery(input: CalendarsDueForResyncQueryInput): FirestoreQueryConstraint[]',
    params: [{ name: 'input', type: 'CalendarsDueForResyncQueryInput', description: '- The type to sweep and the staleness cutoff.', optional: false }],
    description:
      "Returns query constraints for Calendars of a type whose last successful publish (`sat`) is older than the\ngiven instant.\n\nThis is the self-healing backstop: it catches a Calendar whose sweep cleared `s` but whose ICS never\nfinished publishing, and it keeps an `expand`-mode calendar from sliding off the end of its expansion\nwindow without any extra field or mechanism.\n\nNOTE: a Firestore inequality skips documents where the field is absent, so a Calendar that has NEVER\npublished is not matched here. That case is already covered — it still carries `s == true` until its first\nsuccessful sweep, and the ICS StorageFile's own retry / stuck-detection owns everything after that.",
    category: 'maintenance',
    tags: ['maintenance', 'calendar', 'calendars', 'due', 'for', 'resync', 'query', 'calendarsdueforresyncquery', 'constraints', 'type', 'whose', 'last', 'successful', 'publish', 'sat', 'older'],
    example: "const constraints = calendarsDueForResyncQuery({ calendarType: 'demo_profile', before: subDays(new Date(), 7) });",
    queryMode: 'unavailable',
    rules: { list: 'unmatched', collectionGroup: false, reason: 'list-unmatched' },
    factory: calendarsDueForResyncQuery
  },
  {
    slug: 'calendars-flagged-for-sync-query',
    name: 'calendarsFlaggedForSyncQuery',
    module: '@dereekb/firebase',
    subpath: 'model/calendar/calendar.query',
    model: 'Calendar',
    collection: 'cal',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'calendarsFlaggedForSyncQuery(): FirestoreQueryConstraint[]',
    params: [],
    description: 'Returns query constraints for Calendars flagged for sync (`s == true`).\n\nThis is what the hourly sweep iterates.',
    category: 'sweep',
    tags: ['sweep', 'calendar', 'calendars', 'flagged', 'for', 'sync', 'query', 'calendarsflaggedforsyncquery', 'constraints', 'true', 'what', 'hourly', 'iterates'],
    example: 'const constraints = calendarsFlaggedForSyncQuery();',
    queryMode: 'unavailable',
    rules: { list: 'unmatched', collectionGroup: false, reason: 'list-unmatched' },
    factory: calendarsFlaggedForSyncQuery
  },
  {
    slug: 'calendars-for-type-query',
    name: 'calendarsForTypeQuery',
    module: '@dereekb/firebase',
    subpath: 'model/calendar/calendar.query',
    model: 'Calendar',
    collection: 'cal',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'calendarsForTypeQuery(calendarType: CalendarType): FirestoreQueryConstraint[]',
    params: [{ name: 'calendarType', type: 'CalendarType', description: '- The type to filter by.', optional: false }],
    description: 'Returns query constraints for every Calendar of a given type.',
    category: 'lookup',
    tags: ['lookup', 'calendar', 'calendars', 'for', 'type', 'query', 'calendarsfortypequery', 'constraints', 'every', 'given'],
    example: "const constraints = calendarsForTypeQuery('demo_profile');",
    queryMode: 'unavailable',
    rules: { list: 'unmatched', collectionGroup: false, reason: 'list-unmatched' },
    factory: calendarsForTypeQuery
  },
  {
    slug: 'form-spaces-due-for-expiration-query',
    name: 'formSpacesDueForExpirationQuery',
    module: '@dereekb/firebase',
    subpath: 'model/formspace/formspace.query',
    model: 'FormSpace',
    collection: 'fsp',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'formSpacesDueForExpirationQuery(input: FormSpacesDueForExpirationQueryInput): FirestoreQueryConstraint[]',
    params: [{ name: 'input', type: 'FormSpacesDueForExpirationQueryInput', description: '- The pinned cutoff.', optional: false }],
    description:
      'Returns query constraints for FormSpaces whose expiration instant has arrived.\n\nNOTE: a Firestore inequality skips documents where the field is absent, so a space with no `eat` — one\nwhose type does not expire, or one that has already been submitted or expired and had `eat` cleared — is\nnot matched. That absence IS the exclusion mechanism; there is no second flag to keep in step.',
    category: 'cleanup',
    tags: ['cleanup', 'formspace', 'form', 'spaces', 'due', 'for', 'expiration', 'query', 'formspacesdueforexpirationquery', 'space', 'constraints', 'formspaces', 'whose', 'instant', 'has', 'arrived', 'note', 'firestore'],
    example: 'const constraints = formSpacesDueForExpirationQuery({ before: new Date() });',
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: formSpacesDueForExpirationQuery
  },
  {
    slug: 'form-spaces-for-owner-query',
    name: 'formSpacesForOwnerQuery',
    module: '@dereekb/firebase',
    subpath: 'model/formspace/formspace.query',
    model: 'FormSpace',
    collection: 'fsp',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'formSpacesForOwnerQuery(ownerKey: FirebaseAuthOwnershipKey): FirestoreQueryConstraint[]',
    params: [{ name: 'ownerKey', type: 'FirebaseAuthOwnershipKey', description: '- The ownership key to filter by.', optional: false }],
    description: 'Returns query constraints for every FormSpace carrying the given ownership key.\n\nOrdering is deliberately left to the caller/client: a second field here would need a composite index this\npackage has no way to declare.',
    category: 'lookup',
    tags: ['lookup', 'formspace', 'form', 'spaces', 'for', 'owner', 'query', 'formspacesforownerquery', 'space', 'constraints', 'every', 'carrying', 'given', 'ownership', 'key', 'ordering', 'deliberately'],
    example: "const constraints = formSpacesForOwnerQuery('pr/abc123');",
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: formSpacesForOwnerQuery
  },
  {
    slug: 'form-spaces-queued-for-processing-query',
    name: 'formSpacesQueuedForProcessingQuery',
    module: '@dereekb/firebase',
    subpath: 'model/formspace/formspace.query',
    model: 'FormSpace',
    collection: 'fsp',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'formSpacesQueuedForProcessingQuery(): FirestoreQueryConstraint[]',
    params: [],
    description: 'Returns query constraints for FormSpaces awaiting a processing task (`ps == QUEUED_FOR_PROCESSING`).\n\nThis is the backstop sweep: submission normally creates the task inline, so a space that is still sitting\nhere is one whose task creation was lost.',
    category: 'sweep',
    tags: ['sweep', 'formspace', 'form', 'spaces', 'queued', 'for', 'processing', 'query', 'formspacesqueuedforprocessingquery', 'space', 'constraints', 'formspaces', 'awaiting', 'task', 'backstop', 'submission', 'normally', 'creates'],
    example: 'const constraints = formSpacesQueuedForProcessingQuery();',
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: formSpacesQueuedForProcessingQuery
  },
  {
    slug: 'notification-boxes-flagged-for-needs-initialization-query',
    name: 'notificationBoxesFlaggedForNeedsInitializationQuery',
    module: '@dereekb/firebase',
    subpath: 'model/notification/notification.query',
    model: 'NotificationBox',
    collection: 'nb',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'notificationBoxesFlaggedForNeedsInitializationQuery(): FirestoreQueryConstraint[]',
    params: [],
    description: 'Query constraints for finding {@link NotificationBox} documents that need server-side initialization (`s == true`).',
    category: 'init',
    tags: ['init', 'notificationbox', 'notification', 'boxes', 'flagged', 'for', 'needs', 'initialization', 'query', 'notificationboxesflaggedforneedsinitializationquery', 'box', 'constraints', 'finding', 'link', 'documents', 'need', 'server', 'side', 'true'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: notificationBoxesFlaggedForNeedsInitializationQuery
  },
  {
    slug: 'notification-boxes-flagged-invalid-query',
    name: 'notificationBoxesFlaggedInvalidQuery',
    module: '@dereekb/firebase',
    subpath: 'model/notification/notification.query',
    model: 'NotificationBox',
    collection: 'nb',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'notificationBoxesFlaggedInvalidQuery(): FirestoreQueryConstraint[]',
    params: [],
    description: 'Query constraints for finding {@link NotificationBox} documents flagged as invalid (`fi == true`).\n\nUsed by the server to clean up boxes that could not be initialized.',
    category: 'cleanup',
    tags: ['cleanup', 'notificationbox', 'notification', 'boxes', 'flagged', 'invalid', 'query', 'notificationboxesflaggedinvalidquery', 'box', 'constraints', 'finding', 'link', 'documents', 'true', 'used', 'server', 'clean'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: notificationBoxesFlaggedInvalidQuery
  },
  {
    slug: 'notification-logged-event-days-older-than-query',
    name: 'notificationLoggedEventDaysOlderThanQuery',
    module: '@dereekb/firebase',
    subpath: 'model/notification/notification.query',
    model: 'NotificationLoggedEventDay',
    collection: 'nbnle',
    isNested: true,
    scope: 'COLLECTION_GROUP',
    signature: 'notificationLoggedEventDaysOlderThanQuery(retentionDays: number, now?: Date): FirestoreQueryConstraint[]',
    params: [
      { name: 'retentionDays', type: 'number', description: '- Number of days of history to retain; days strictly older than `now - retentionDays` match.', optional: false },
      { name: 'now', type: 'Date', description: '- Reference time for the cutoff (defaults to current time)', optional: true }
    ],
    description:
      'Query constraints for finding {@link NotificationLoggedEventDay} documents whose ISO day string\nis older than `now - retentionDays`.\n\nIntended for use against the {@link NotificationLoggedEventDayFirestoreCollectionGroup} during\nscheduled retention cleanup. Documents older than the cutoff (and their nested page subcollection\ncontents) should be deleted.\n\nUses the `d` field rather than document ID — Firestore collection-group queries cannot filter on\n`FieldPath.documentId()` with a bare day string (it requires a full path). The `d` field stores\nthe same ISO 8601 day string as the document ID and supports a plain inequality.',
    category: 'cleanup',
    tags: ['cleanup', 'notificationloggedeventday', 'notification', 'logged', 'event', 'days', 'older', 'than', 'query', 'notificationloggedeventdaysolderthanquery', 'day', 'constraints', 'finding', 'link', 'documents', 'whose', 'iso', 'string', 'now'],
    queryMode: 'parent-child',
    rules: { list: 'allowed', collectionGroup: false, reason: 'no-collection-group-rule', parentPaths: ['nb/{notificationBox}'] },
    factory: notificationLoggedEventDaysOlderThanQuery
  },
  {
    slug: 'notification-summaries-flagged-for-needs-initialization-query',
    name: 'notificationSummariesFlaggedForNeedsInitializationQuery',
    module: '@dereekb/firebase',
    subpath: 'model/notification/notification.query',
    model: 'NotificationSummary',
    collection: 'ns',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'notificationSummariesFlaggedForNeedsInitializationQuery(): FirestoreQueryConstraint[]',
    params: [],
    description: 'Query constraints for finding {@link NotificationSummary} documents that need server-side initialization (`s == true`).',
    category: 'init',
    tags: ['init', 'notificationsummary', 'notification', 'summaries', 'flagged', 'for', 'needs', 'initialization', 'query', 'notificationsummariesflaggedforneedsinitializationquery', 'summary', 'constraints', 'finding', 'link', 'documents', 'need', 'server', 'side', 'true'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: notificationSummariesFlaggedForNeedsInitializationQuery
  },
  {
    slug: 'notification-user-has-exclusion-query',
    name: 'notificationUserHasExclusionQuery',
    module: '@dereekb/firebase',
    subpath: 'model/notification/notification.query',
    model: 'NotificationUser',
    collection: 'nu',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'notificationUserHasExclusionQuery(exclusionId: ArrayOrValue<NotificationBoxSendExclusion>): FirestoreQueryConstraint[]',
    params: [{ name: 'exclusionId', type: 'ArrayOrValue<NotificationBoxSendExclusion>', description: '- One or more box IDs or collection name prefixes to match against.', optional: false }],
    description: 'Query constraints for finding {@link NotificationUser} documents that have any of the given exclusion IDs in their `x` array.',
    category: 'lookup',
    tags: ['lookup', 'notificationuser', 'notification', 'user', 'has', 'exclusion', 'query', 'notificationuserhasexclusionquery', 'constraints', 'finding', 'link', 'documents', 'have', 'any', 'given', 'ids'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: notificationUserHasExclusionQuery
  },
  {
    slug: 'notification-users-flagged-for-needs-sync-query',
    name: 'notificationUsersFlaggedForNeedsSyncQuery',
    module: '@dereekb/firebase',
    subpath: 'model/notification/notification.query',
    model: 'NotificationUser',
    collection: 'nu',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'notificationUsersFlaggedForNeedsSyncQuery(): FirestoreQueryConstraint[]',
    params: [],
    description: 'Query constraints for finding {@link NotificationUser} documents that have pending config syncs (`ns == true`).\n\nUsed by the server to discover users whose configs need to be synced to their NotificationBox recipients.',
    category: 'sweep',
    tags: ['sweep', 'notificationuser', 'notification', 'users', 'flagged', 'for', 'needs', 'sync', 'query', 'notificationusersflaggedforneedssyncquery', 'user', 'constraints', 'finding', 'link', 'documents', 'have', 'pending', 'config', 'syncs'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: notificationUsersFlaggedForNeedsSyncQuery
  },
  {
    slug: 'notifications-newest-first-query',
    name: 'notificationsNewestFirstQuery',
    module: '@dereekb/firebase',
    subpath: 'model/notification/notification.query',
    model: 'Notification',
    collection: 'nbn',
    isNested: true,
    scope: 'COLLECTION',
    signature: 'notificationsNewestFirstQuery(): FirestoreQueryConstraint[]',
    params: [],
    description:
      "Query constraints for listing the {@link Notification} documents in one {@link NotificationBox}, newest first.\n\nRun against a single box's notification collection — this is how an admin finds the notifications sent to a\nmodel (e.g. every notification for a profile) when their ids are auto-generated and not otherwise known. Pair it\nwith a limit; a busy box can hold many notifications between cleanup sweeps.",
    category: 'lookup',
    tags: ['lookup', 'notification', 'notifications', 'newest', 'first', 'query', 'notificationsnewestfirstquery', 'constraints', 'listing', 'link', 'documents', 'one', 'notificationbox', 'run', 'against'],
    queryMode: 'parent-child',
    rules: { list: 'allowed', collectionGroup: false, reason: 'nested-collection-scope', parentPaths: ['nb/{notificationBox}'] },
    factory: notificationsNewestFirstQuery
  },
  {
    slug: 'notifications-past-send-at-time-query',
    name: 'notificationsPastSendAtTimeQuery',
    module: '@dereekb/firebase',
    subpath: 'model/notification/notification.query',
    model: 'Notification',
    collection: 'nbn',
    isNested: true,
    scope: 'COLLECTION_GROUP',
    signature: 'notificationsPastSendAtTimeQuery(now?: Date): FirestoreQueryConstraint[]',
    params: [{ name: 'now', type: 'Date', description: '- Reference time for the `sat` comparison (defaults to current time)', optional: true }],
    description: 'Query constraints for finding {@link Notification} documents that are ready to be sent\n(not done and `sat` is in the past).\n\nThis is the primary query used by the send queue processor.',
    category: 'sweep',
    tags: ['sweep', 'notification', 'notifications', 'past', 'send', 'at', 'time', 'query', 'notificationspastsendattimequery', 'constraints', 'finding', 'link', 'documents', 'ready', 'sent', 'not', 'done'],
    queryMode: 'parent-child',
    rules: { list: 'allowed', collectionGroup: false, reason: 'no-collection-group-rule', parentPaths: ['nb/{notificationBox}'] },
    factory: notificationsPastSendAtTimeQuery
  },
  {
    slug: 'notifications-ready-for-cleanup-query',
    name: 'notificationsReadyForCleanupQuery',
    module: '@dereekb/firebase',
    subpath: 'model/notification/notification.query',
    model: 'Notification',
    collection: 'nbn',
    isNested: true,
    scope: 'COLLECTION_GROUP',
    signature: 'notificationsReadyForCleanupQuery(): FirestoreQueryConstraint[]',
    params: [],
    description: 'Query constraints for finding {@link Notification} documents marked as done (`d == true`)\nand ready to be archived to {@link NotificationWeek} and then deleted.',
    category: 'cleanup',
    tags: ['cleanup', 'notification', 'notifications', 'ready', 'for', 'query', 'notificationsreadyforcleanupquery', 'constraints', 'finding', 'link', 'documents', 'marked', 'done', 'true', 'archived'],
    queryMode: 'parent-child',
    rules: { list: 'allowed', collectionGroup: false, reason: 'no-collection-group-rule', parentPaths: ['nb/{notificationBox}'] },
    factory: notificationsReadyForCleanupQuery
  },
  {
    slug: 'oidc-client-entries-by-owner-query',
    name: 'oidcClientEntriesByOwnerQuery',
    module: '@dereekb/firebase',
    subpath: 'model/oidcmodel/oidcmodel.query',
    model: 'OidcEntry',
    collection: 'oidc_e',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'oidcClientEntriesByOwnerQuery(ownershipKey: FirebaseAuthOwnershipKey): FirestoreQueryConstraint[]',
    params: [{ name: 'ownershipKey', type: 'FirebaseAuthOwnershipKey', description: '- The ownership key identifying the owner.', optional: false }],
    description: 'Query for OidcEntry Client documents owned by a specific user.',
    category: 'lookup',
    tags: ['lookup', 'oidcentry', 'oidc', 'client', 'entries', 'by', 'owner', 'query', 'oidccliententriesbyownerquery', 'entry', 'documents', 'owned', 'specific', 'user'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: oidcClientEntriesByOwnerQuery
  },
  {
    slug: 'oidc-entries-by-client-id-query',
    name: 'oidcEntriesByClientIdQuery',
    module: '@dereekb/firebase',
    subpath: 'model/oidcmodel/oidcmodel.query',
    model: 'OidcEntry',
    collection: 'oidc_e',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'oidcEntriesByClientIdQuery(type: OidcEntryType, clientId: string): FirestoreQueryConstraint[]',
    params: [
      { name: 'type', type: 'OidcEntryType', description: '- The OIDC entry type to filter by.', optional: false },
      { name: 'clientId', type: 'string', description: '- The OAuth client ID to match.', optional: false }
    ],
    description: 'Query for OidcEntry documents with a specific type and clientId.',
    category: 'lookup',
    tags: ['lookup', 'oidcentry', 'oidc', 'entries', 'by', 'client', 'id', 'query', 'oidcentriesbyclientidquery', 'entry', 'documents', 'specific', 'type', 'clientid'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: oidcEntriesByClientIdQuery
  },
  {
    slug: 'oidc-entries-by-grant-id-query',
    name: 'oidcEntriesByGrantIdQuery',
    module: '@dereekb/firebase',
    subpath: 'model/oidcmodel/oidcmodel.query',
    model: 'OidcEntry',
    collection: 'oidc_e',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'oidcEntriesByGrantIdQuery(type: OidcEntryType, grantId: string): FirestoreQueryConstraint[]',
    params: [
      { name: 'type', type: 'OidcEntryType', description: '- The OIDC entry type to filter by.', optional: false },
      { name: 'grantId', type: 'string', description: '- The grant ID to match.', optional: false }
    ],
    description: 'Query for OidcEntry documents with a specific type and grantId.',
    category: 'lookup',
    tags: ['lookup', 'oidcentry', 'oidc', 'entries', 'by', 'grant', 'id', 'query', 'oidcentriesbygrantidquery', 'entry', 'documents', 'specific', 'type', 'grantid'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: oidcEntriesByGrantIdQuery
  },
  {
    slug: 'oidc-entries-by-uid-query',
    name: 'oidcEntriesByUidQuery',
    module: '@dereekb/firebase',
    subpath: 'model/oidcmodel/oidcmodel.query',
    model: 'OidcEntry',
    collection: 'oidc_e',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'oidcEntriesByUidQuery(type: OidcEntryType, uid: FirebaseAuthUserId): FirestoreQueryConstraint[]',
    params: [
      { name: 'type', type: 'OidcEntryType', description: '- The OIDC entry type to filter by.', optional: false },
      { name: 'uid', type: 'FirebaseAuthUserId', description: '- The Firebase user ID to match.', optional: false }
    ],
    description: 'Query for OidcEntry documents with a specific type and uid.',
    category: 'lookup',
    tags: ['lookup', 'oidcentry', 'oidc', 'entries', 'by', 'uid', 'query', 'oidcentriesbyuidquery', 'entry', 'documents', 'specific', 'type'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: oidcEntriesByUidQuery
  },
  {
    slug: 'oidc-entries-by-user-code-query',
    name: 'oidcEntriesByUserCodeQuery',
    module: '@dereekb/firebase',
    subpath: 'model/oidcmodel/oidcmodel.query',
    model: 'OidcEntry',
    collection: 'oidc_e',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'oidcEntriesByUserCodeQuery(type: OidcEntryType, userCode: string): FirestoreQueryConstraint[]',
    params: [
      { name: 'type', type: 'OidcEntryType', description: '- The OIDC entry type to filter by.', optional: false },
      { name: 'userCode', type: 'string', description: '- The user code to match.', optional: false }
    ],
    description: 'Query for OidcEntry documents with a specific type and userCode.',
    category: 'lookup',
    tags: ['lookup', 'oidcentry', 'oidc', 'entries', 'by', 'user', 'code', 'query', 'oidcentriesbyusercodequery', 'entry', 'documents', 'specific', 'type', 'usercode'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: oidcEntriesByUserCodeQuery
  },
  {
    slug: 'oidc-entries-with-type-query',
    name: 'oidcEntriesWithTypeQuery',
    module: '@dereekb/firebase',
    subpath: 'model/oidcmodel/oidcmodel.query',
    model: 'OidcEntry',
    collection: 'oidc_e',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'oidcEntriesWithTypeQuery(type: OidcEntryType): FirestoreQueryConstraint[]',
    params: [{ name: 'type', type: 'OidcEntryType', description: '- The OIDC entry type to filter by.', optional: false }],
    description: 'Query for OidcEntry documents with a specific type.',
    category: 'lookup',
    tags: ['lookup', 'oidcentry', 'oidc', 'entries', 'with', 'type', 'query', 'oidcentrieswithtypequery', 'entry', 'documents', 'specific'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: oidcEntriesWithTypeQuery
  },
  {
    slug: 'oidc-grant-entries-by-uid-query',
    name: 'oidcGrantEntriesByUidQuery',
    module: '@dereekb/firebase',
    subpath: 'model/oidcmodel/oidcmodel.query',
    model: 'OidcEntry',
    collection: 'oidc_e',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'oidcGrantEntriesByUidQuery(uid: FirebaseAuthUserId): FirestoreQueryConstraint[]',
    params: [{ name: 'uid', type: 'FirebaseAuthUserId', description: '- The Firebase user id the grants were issued to.', optional: false }],
    description: 'Query for OidcEntry Grant documents issued to a specific user.\n\nUsed by the "apps with access to my account" UI to list every outstanding\ngrant the signed-in user has authorized.',
    category: 'lookup',
    tags: ['lookup', 'oidcentry', 'oidc', 'grant', 'entries', 'by', 'uid', 'query', 'oidcgrantentriesbyuidquery', 'entry', 'documents', 'issued', 'specific', 'user', 'used', 'apps', 'access', 'account'],
    dispatcher: true,
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: oidcGrantEntriesByUidQuery
  },
  {
    slug: 'open-router-prompts-with-state-query',
    name: 'openRouterPromptsWithStateQuery',
    module: '@dereekb/openrouter/firebase',
    subpath: 'openrouter.query',
    model: 'OpenRouterPrompt',
    collection: 'orp',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'openRouterPromptsWithStateQuery(params: OpenRouterPromptsWithStateQueryParams): FirestoreQueryConstraint[]',
    params: [{ name: 'params', type: 'OpenRouterPromptsWithStateQueryParams', description: '- The state to match.', optional: false }],
    description:
      "Query for the prompts in one lifecycle state.\n\nNeeds no composite index, and is deliberately kept that way. Unordered, so pagination falls through to\nFirestore's implicit `__name__` order — which for this model is the prompt's own readable key, already\nthe order a listing wants — and state is the only filter axis: pairing it with an `array-contains` on\n`t` would buy a composite index for a collection measured in dozens of documents.",
    category: 'admin',
    tags: ['admin', 'openrouterprompt', 'open', 'router', 'prompts', 'with', 'state', 'query', 'openrouterpromptswithstatequery', 'prompt', 'one', 'lifecycle', 'needs', 'composite', 'index', 'deliberately', 'kept', 'way'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: openRouterPromptsWithStateQuery
  },
  {
    slug: 'open-router-run-tasks-expired-query',
    name: 'openRouterRunTasksExpiredQuery',
    module: '@dereekb/openrouter/firebase',
    subpath: 'openrouter.query',
    model: 'OpenRouterRunTask',
    collection: 'orrt',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'openRouterRunTasksExpiredQuery(params: OpenRouterRunTasksExpiredQueryParams): FirestoreQueryConstraint[]',
    params: [{ name: 'params', type: 'OpenRouterRunTasksExpiredQueryParams', description: '- The retention cutoff and page limit.', optional: false }],
    description:
      "Query for run tasks past their retention age, for deletion. Matches EVERY state, `RUNNING` included —\nsee {@link OPENROUTER_RUN_TASK_MAX_AGE} for why the ceiling is the whole requirement.\n\nOrdered by `qat` with no state filter, so it needs no composite index at all: a single-field range with\na matching order is served by Firestore's automatic single-field index.\n\nFirestore's NATIVE TTL policy cannot do this job, for the same reason the cutoff goes through\n`whereDateIsOnOrBefore` rather than a bare `where('qat', '<=', date)`: `firestoreDate` persists an\nISO8601 STRING, and a TTL policy only deletes on a `Timestamp` field. Pointed at `qat` it would\nsilently never fire. The app-level sweep is the mechanism here, not a stopgap for one.",
    category: 'cleanup',
    tags: ['cleanup', 'openrouterruntask', 'open', 'router', 'run', 'tasks', 'expired', 'query', 'openrouterruntasksexpiredquery', 'task', 'past', 'their', 'retention', 'age', 'deletion', 'matches', 'every', 'state'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: openRouterRunTasksExpiredQuery
  },
  {
    slug: 'open-router-run-tasks-reclaimable-query',
    name: 'openRouterRunTasksReclaimableQuery',
    module: '@dereekb/openrouter/firebase',
    subpath: 'openrouter.query',
    model: 'OpenRouterRunTask',
    collection: 'orrt',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'openRouterRunTasksReclaimableQuery(params: OpenRouterRunTasksReclaimableQueryParams): FirestoreQueryConstraint[]',
    params: [{ name: 'params', type: 'OpenRouterRunTasksReclaimableQueryParams', description: '- The page limit and lease cutoff.', optional: false }],
    description:
      "Query for RUNNING run tasks whose lease has gone stale — crash recovery.\n\nSeparate from {@link openRouterRunTasksRunnableQuery} because it needs a range filter on `lat`, and\nFirestore allows the range filter on only one field, which the ordering must then lead with.\n\nThe cutoff goes through `whereDateIsOnOrBefore` rather than a bare `where('lat', '<=', date)`:\n`firestoreDate` persists an ISO8601 STRING, so comparing the field against a `Date` compares a string\nto a timestamp and matches nothing — silently, with no error and an empty page, which reads exactly\nlike \"no crashed sweeps to recover\".",
    category: 'sweep',
    tags: ['sweep', 'openrouterruntask', 'open', 'router', 'run', 'tasks', 'reclaimable', 'query', 'openrouterruntasksreclaimablequery', 'task', 'running', 'whose', 'lease', 'has', 'gone', 'stale', 'crash', 'recovery'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: openRouterRunTasksReclaimableQuery
  },
  {
    slug: 'open-router-run-tasks-runnable-query',
    name: 'openRouterRunTasksRunnableQuery',
    module: '@dereekb/openrouter/firebase',
    subpath: 'openrouter.query',
    model: 'OpenRouterRunTask',
    collection: 'orrt',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'openRouterRunTasksRunnableQuery(params: OpenRouterRunTasksRunnableQueryParams): FirestoreQueryConstraint[]',
    params: [{ name: 'params', type: 'OpenRouterRunTasksRunnableQueryParams', description: '- The page limit.', optional: false }],
    description:
      "Query for the run tasks a sweep may execute, oldest-queued first.\n\nQueue order is the ONLY order, and deliberately so. A priority column costs a second composite index\nand buys a second failure mode: Firestore sorts `null` before every number, so one task written without\na priority jumps the entire queue. Delaying a run is `NotificationTask`'s job — it owns the delayed\nfiring — which leaves nothing for a priority here to express.",
    category: 'sweep',
    tags: ['sweep', 'openrouterruntask', 'open', 'router', 'run', 'tasks', 'runnable', 'query', 'openrouterruntasksrunnablequery', 'task', 'may', 'execute', 'oldest', 'queued', 'first', 'queue', 'order', 'only'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: openRouterRunTasksRunnableQuery
  },
  {
    slug: 'profile-with-username-query',
    name: 'profileWithUsernameQuery',
    module: 'demo-firebase',
    subpath: 'model/profile/profile.query',
    model: 'Profile',
    collection: 'pr',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'profileWithUsernameQuery(params: ProfileWithUsernameQueryParams): FirestoreQueryConstraint[]',
    params: [{ name: 'params', type: 'ProfileWithUsernameQueryParams', description: '- The username to match.', optional: false }],
    description: 'Query for the profile holding a given unique username.',
    category: 'lookup',
    tags: ['lookup', 'profile', 'with', 'username', 'query', 'profilewithusernamequery', 'holding', 'given', 'unique'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: profileWithUsernameQuery
  },
  {
    slug: 'published-guestbook-entries-query',
    name: 'publishedGuestbookEntriesQuery',
    module: 'demo-firebase',
    subpath: 'model/guestbook/guestbook.query',
    model: 'GuestbookEntry',
    collection: 'gbe',
    isNested: true,
    scope: 'COLLECTION_GROUP',
    signature: 'publishedGuestbookEntriesQuery(params: PublishedGuestbookEntriesQueryParams): FirestoreQueryConstraint[]',
    params: [{ name: 'params', type: 'PublishedGuestbookEntriesQueryParams', description: '- The published state to match.', optional: false }],
    description:
      "Query for the guestbook entries in the given published state.\n\nDeclared at `COLLECTION_GROUP` scope because it is used both within a single guestbook's `gbe`\nsubcollection and across the `gbe` collection group. Firestore auto-indexes single fields at\nCOLLECTION scope only, so the group-scoped use needs the explicit `fieldOverrides` entry this\nscope tag emits — without it the group query fails `FAILED_PRECONDITION` against a real project\n(the emulator does not enforce indexes, so it passes locally either way).",
    category: 'listing',
    tags: ['listing', 'guestbookentry', 'published', 'guestbook', 'entries', 'query', 'publishedguestbookentriesquery', 'entry', 'given', 'state', 'declared', 'collection', 'group', 'scope', 'because', 'used'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: true, parentPaths: ['gb/{guestbook}'] },
    factory: publishedGuestbookEntriesQuery
  },
  {
    slug: 'published-guestbooks-query',
    name: 'publishedGuestbooksQuery',
    module: 'demo-firebase',
    subpath: 'model/guestbook/guestbook.query',
    model: 'Guestbook',
    collection: 'gb',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'publishedGuestbooksQuery(params: PublishedGuestbooksQueryParams): FirestoreQueryConstraint[]',
    params: [{ name: 'params', type: 'PublishedGuestbooksQueryParams', description: '- The published state to match.', optional: false }],
    description: 'Query for the guestbooks in the given published state.',
    category: 'listing',
    tags: ['listing', 'guestbook', 'published', 'guestbooks', 'query', 'publishedguestbooksquery', 'given', 'state'],
    queryMode: 'model',
    rules: { list: 'allowed', collectionGroup: false },
    factory: publishedGuestbooksQuery
  },
  {
    slug: 'storage-file-flagged-for-sync-with-groups-query',
    name: 'storageFileFlaggedForSyncWithGroupsQuery',
    module: '@dereekb/firebase',
    subpath: 'model/storagefile/storagefile.query',
    model: 'StorageFile',
    collection: 'sf',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'storageFileFlaggedForSyncWithGroupsQuery(): FirestoreQueryConstraint[]',
    params: [],
    description: 'Returns query constraints for StorageFiles flagged for group synchronization (`gs == true`).\n\nUsed by the sync service to find files whose group memberships need to be propagated.',
    category: 'sweep',
    tags: ['sweep', 'storagefile', 'storage', 'file', 'flagged', 'for', 'sync', 'with', 'groups', 'query', 'storagefileflaggedforsyncwithgroupsquery', 'constraints', 'storagefiles', 'group', 'synchronization', 'true', 'used', 'service', 'find'],
    queryMode: 'unavailable',
    rules: { list: 'unmatched', collectionGroup: false, reason: 'list-unmatched' },
    factory: storageFileFlaggedForSyncWithGroupsQuery
  },
  {
    slug: 'storage-file-groups-flagged-for-content-regeneration-query',
    name: 'storageFileGroupsFlaggedForContentRegenerationQuery',
    module: '@dereekb/firebase',
    subpath: 'model/storagefile/storagefile.query',
    model: 'StorageFileGroup',
    collection: 'sfg',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'storageFileGroupsFlaggedForContentRegenerationQuery(): FirestoreQueryConstraint[]',
    params: [],
    description: 'Returns query constraints for StorageFileGroups flagged for content regeneration (`re == true`).',
    category: 'sweep',
    tags: ['sweep', 'storagefilegroup', 'storage', 'file', 'groups', 'flagged', 'for', 'content', 'regeneration', 'query', 'storagefilegroupsflaggedforcontentregenerationquery', 'group', 'constraints', 'storagefilegroups', 'true'],
    queryMode: 'unavailable',
    rules: { list: 'unmatched', collectionGroup: false, reason: 'list-unmatched' },
    factory: storageFileGroupsFlaggedForContentRegenerationQuery
  },
  {
    slug: 'storage-file-groups-flagged-for-needs-initialization-query',
    name: 'storageFileGroupsFlaggedForNeedsInitializationQuery',
    module: '@dereekb/firebase',
    subpath: 'model/storagefile/storagefile.query',
    model: 'StorageFileGroup',
    collection: 'sfg',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'storageFileGroupsFlaggedForNeedsInitializationQuery(): FirestoreQueryConstraint[]',
    params: [],
    description: "Returns query constraints for StorageFileGroups that need initialization (`s == true`).\n\nUsed by the initialization service to find newly-created groups that haven't been synced yet.",
    category: 'init',
    tags: ['init', 'storagefilegroup', 'storage', 'file', 'groups', 'flagged', 'for', 'needs', 'initialization', 'query', 'storagefilegroupsflaggedforneedsinitializationquery', 'group', 'constraints', 'storagefilegroups', 'need', 'true', 'used', 'service', 'find', 'newly'],
    queryMode: 'unavailable',
    rules: { list: 'unmatched', collectionGroup: false, reason: 'list-unmatched' },
    factory: storageFileGroupsFlaggedForNeedsInitializationQuery
  },
  {
    slug: 'storage-file-groups-flagged-invalid-query',
    name: 'storageFileGroupsFlaggedInvalidQuery',
    module: '@dereekb/firebase',
    subpath: 'model/storagefile/storagefile.query',
    model: 'StorageFileGroup',
    collection: 'sfg',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'storageFileGroupsFlaggedInvalidQuery(): FirestoreQueryConstraint[]',
    params: [],
    description: 'Returns query constraints for StorageFileGroups flagged as invalid (`fi == true`).\n\nInvalid groups are typically cleaned up (deleted along with their associated files).',
    category: 'cleanup',
    tags: ['cleanup', 'storagefilegroup', 'storage', 'file', 'groups', 'flagged', 'invalid', 'query', 'storagefilegroupsflaggedinvalidquery', 'group', 'constraints', 'storagefilegroups', 'true', 'typically', 'cleaned', 'deleted', 'along', 'their'],
    queryMode: 'unavailable',
    rules: { list: 'unmatched', collectionGroup: false, reason: 'list-unmatched' },
    factory: storageFileGroupsFlaggedInvalidQuery
  },
  {
    slug: 'storage-file-purpose-and-user-query',
    name: 'storageFilePurposeAndUserQuery',
    module: '@dereekb/firebase',
    subpath: 'model/storagefile/storagefile.query',
    model: 'StorageFile',
    collection: 'sf',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'storageFilePurposeAndUserQuery(input: StorageFilePurposeAndUserQueryInput): FirestoreQueryConstraint[]',
    params: [{ name: 'input', type: 'StorageFilePurposeAndUserQueryInput', description: '- The user, purpose, and optional subgroup to filter by.', optional: false }],
    description: 'Returns query constraints for StorageFiles matching a specific purpose and user,\nwith optional subgroup filtering.',
    category: 'lookup',
    tags: ['lookup', 'storagefile', 'storage', 'file', 'purpose', 'and', 'user', 'query', 'storagefilepurposeanduserquery', 'constraints', 'storagefiles', 'matching', 'specific', 'optional', 'subgroup', 'filtering'],
    skip: true,
    queryMode: 'unavailable',
    rules: { list: 'unmatched', collectionGroup: false, reason: 'list-unmatched' },
    factory: storageFilePurposeAndUserQuery
  },
  {
    slug: 'storage-files-for-form-space-query',
    name: 'storageFilesForFormSpaceQuery',
    module: '@dereekb/firebase',
    subpath: 'model/formspace/formspace.query',
    model: 'StorageFile',
    collection: 'sf',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'storageFilesForFormSpaceQuery(formSpaceKey: FormSpaceKey): FirestoreQueryConstraint[]',
    params: [{ name: 'formSpaceKey', type: 'FormSpaceKey', description: '- The FormSpace whose files to select.', optional: false }],
    description: "Returns query constraints for every StorageFile that belongs to a FormSpace.\n\nA single `array-contains` on the group id, which Firestore serves from its automatic array index — the\nFormSpace's own group id is the only handle needed, so nothing here requires a composite index.",
    category: 'lookup',
    tags: ['lookup', 'storagefile', 'storage', 'files', 'for', 'form', 'space', 'query', 'storagefilesforformspacequery', 'file', 'constraints', 'every', 'belongs', 'formspace', 'single', 'array', 'contains', 'group'],
    example: "const constraints = storageFilesForFormSpaceQuery('fsp/abc123');",
    skip: true,
    queryMode: 'unavailable',
    rules: { list: 'unmatched', collectionGroup: false, reason: 'list-unmatched' },
    factory: storageFilesForFormSpaceQuery
  },
  {
    slug: 'storage-files-queued-for-delete-query',
    name: 'storageFilesQueuedForDeleteQuery',
    module: '@dereekb/firebase',
    subpath: 'model/storagefile/storagefile.query',
    model: 'StorageFile',
    collection: 'sf',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'storageFilesQueuedForDeleteQuery(now?: Maybe<Date>): FirestoreQueryConstraint[]',
    params: [{ name: 'now', type: 'Maybe<Date>', description: '- Reference time for comparison; defaults to current time.', optional: true }],
    description: 'Returns query constraints for StorageFiles whose scheduled delete date (`sdat`) has passed.\n\nUsed by the cleanup service to find files ready for permanent deletion.',
    category: 'cleanup',
    tags: ['cleanup', 'storagefile', 'storage', 'files', 'queued', 'for', 'delete', 'query', 'storagefilesqueuedfordeletequery', 'file', 'constraints', 'storagefiles', 'whose', 'scheduled', 'date', 'sdat', 'has', 'passed'],
    example: 'const constraints = storageFilesQueuedForDeleteQuery();',
    queryMode: 'unavailable',
    rules: { list: 'unmatched', collectionGroup: false, reason: 'list-unmatched' },
    factory: storageFilesQueuedForDeleteQuery
  },
  {
    slug: 'storage-files-queued-for-processing-query',
    name: 'storageFilesQueuedForProcessingQuery',
    module: '@dereekb/firebase',
    subpath: 'model/storagefile/storagefile.query',
    model: 'StorageFile',
    collection: 'sf',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'storageFilesQueuedForProcessingQuery(): FirestoreQueryConstraint[]',
    params: [],
    description: 'Returns query constraints for StorageFiles with `ps == QUEUED_FOR_PROCESSING`.\n\nUsed by the server action service to find files awaiting processing task creation.',
    category: 'sweep',
    tags: ['sweep', 'storagefile', 'storage', 'files', 'queued', 'for', 'processing', 'query', 'storagefilesqueuedforprocessingquery', 'file', 'constraints', 'storagefiles', 'used', 'server', 'action', 'service', 'find', 'awaiting'],
    example: 'const constraints = storageFilesQueuedForProcessingQuery();\nconst results = await collection.query(constraints);',
    queryMode: 'unavailable',
    rules: { list: 'unmatched', collectionGroup: false, reason: 'list-unmatched' },
    factory: storageFilesQueuedForProcessingQuery
  },
  {
    slug: 'user-external-connections-with-connected-provider-query',
    name: 'userExternalConnectionsWithConnectedProviderQuery',
    module: '@dereekb/firebase',
    subpath: 'model/userexternalconnection/userexternalconnection.query',
    model: 'UserExternalConnection',
    collection: 'uec',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'userExternalConnectionsWithConnectedProviderQuery(providerType: UserExternalConnectionProviderType): FirestoreQueryConstraint[]',
    params: [{ name: 'providerType', type: 'UserExternalConnectionProviderType', description: '- The provider type to search for.', optional: false }],
    description:
      'Query for the UserExternalConnection documents that are currently connected to the given provider.\n\nThis is the single reason the derived `c` array exists: with one document per user, provider ids\nare map keys, and Firestore cannot query across map keys.\n\nOnly `connected` entries are members of `c`, so this never returns a user whose credentials are in\nthe `error` or `disconnected` state.',
    category: 'misc',
    tags: ['misc', 'userexternalconnection', 'user', 'external', 'connections', 'with', 'connected', 'provider', 'query', 'userexternalconnectionswithconnectedproviderquery', 'connection', 'documents', 'currently', 'given', 'single', 'reason', 'derived', 'array', 'exists'],
    queryMode: 'unavailable',
    rules: { list: 'denied', collectionGroup: false, reason: 'list-denied' },
    factory: userExternalConnectionsWithConnectedProviderQuery
  },
  {
    slug: 'user-external-connections-with-external-account-query',
    name: 'userExternalConnectionsWithExternalAccountQuery',
    module: '@dereekb/firebase',
    subpath: 'model/userexternalconnection/userexternalconnection.query',
    model: 'UserExternalConnection',
    collection: 'uec',
    isNested: false,
    scope: 'COLLECTION',
    signature: 'userExternalConnectionsWithExternalAccountQuery(input: UserExternalConnectionExternalAccountKeyInput): FirestoreQueryConstraint[]',
    params: [{ name: 'input', type: 'UserExternalConnectionExternalAccountKeyInput', description: '- The provider type and external account id to search for.', optional: false }],
    description:
      'Query for the UserExternalConnection document holding the given third-party account.\n\nThe sign-in counterpart of {@link userExternalConnectionsWithConnectedProviderQuery}: that one\nasks "which users are connected to this provider?", this one asks "which user IS this account?".\nBoth exist because a per-user document makes `e.<provider>.ea` unqueryable.\n\nMatches at ANY entry status — see the `ec` field docs. Expect at most one result when the\nprovider\'s policy declares the connection unique, but the caller must still handle more than one:\nuniqueness is enforced at write time and a provider may only have started enforcing it recently.',
    category: 'misc',
    tags: ['misc', 'userexternalconnection', 'user', 'external', 'connections', 'with', 'account', 'query', 'userexternalconnectionswithexternalaccountquery', 'connection', 'document', 'holding', 'given', 'third', 'party', 'sign', 'counterpart', 'link'],
    queryMode: 'unavailable',
    rules: { list: 'denied', collectionGroup: false, reason: 'list-denied' },
    factory: userExternalConnectionsWithExternalAccountQuery
  }
];
