/**
 * `dbx_explain_rule` tool.
 *
 * Two modes:
 *   1. **Lookup** — when `code` is supplied, returns the full documentation
 *      block for that rule (title, severity, source tool, what-it-flags,
 *      when-it-applies, when-it-does-NOT-apply, canonical fix, optional fix
 *      template, optional see-also links). Misremembered codes trigger a
 *      substring search across the catalog (`searchRules(...)`) and the
 *      result lists the top candidates so the caller can re-issue.
 *   2. **List** — when `code` is omitted, returns a compact catalog listing.
 *      Optional `source` / `severity` filters narrow the listing to one
 *      validator's rules or one severity tier.
 *
 * Pure data — no AST, no file I/O. Backed by the catalog generated by
 * `scripts/extract-rule-catalog.mjs` from the per-cluster `codes.ts`
 * enum members.
 */

import { type Tool } from '@modelcontextprotocol/sdk/types.js';
import { type } from 'arktype';
import { findRule, formatRuleAsJson, formatRuleAsMarkdown, RULE_CATALOG, searchRules } from './rule-catalog/index.js';
import type { RuleEntry, RuleSeverity, RuleSource } from './rule-catalog/types.js';
import { toolError, type DbxTool, type ToolResult } from './types.js';

const ExplainRuleArgsType = type({
  'code?': 'string',
  'source?': 'string',
  'severity?': "'error' | 'warning'",
  'format?': "'markdown' | 'json'"
});

const TOOL: Tool = {
  name: 'dbx_explain_rule',
  description: [
    'Explain a validation rule by code, or list the rule catalog.',
    '',
    '**Lookup mode** (default — when `code` is supplied): returns the title, severity, source tool, what it flags, when it applies, when it does NOT apply, canonical fix, optional fix template, and any see-also references.',
    '',
    '**List mode** (when `code` is omitted): returns a compact catalog listing as `\\`CODE\\` (source, severity) — title`. Optional `source` / `severity` filters narrow the listing.',
    '',
    'Use lookup when:',
    '- A validator emitted a code (e.g. `MODEL_COLLECTION_TYPE_WRONG_GENERIC` or `STORAGEFILE_GROUP_IDS_FUNCTION_MISSING`) and you want to know whether the diagnostic actually applies to your case.',
    '- You need the canonical helper-function template for the fix without round-tripping through `dbx_artifact_file_convention`.',
    '- You misremember a code — pass your best guess; an unknown code returns the top 5 catalog candidates.',
    '',
    'Use list when:',
    "- You want to see every rule a given validator emits (`source: 'dbx_model_validate'`).",
    "- You want all warnings (`severity: 'warning'`) so you can audit which findings are advisory.",
    '- You want a one-line overview of every rule for documentation.',
    '',
    'Inputs:',
    '- `code` (optional): the rule code (case-insensitive). Triggers lookup mode.',
    '- `source` (optional): list-mode filter — restricts results to one validator (e.g. `dbx_model_validate`, `dbx_storagefile_m_validate_app`).',
    '- `severity` (optional): list-mode filter — `error` or `warning`.',
    '- `format` (optional): `markdown` (default) or `json`.'
  ].join('\n'),
  inputSchema: {
    type: 'object',
    properties: {
      code: { type: 'string', description: 'The rule code, e.g. `MODEL_COLLECTION_TYPE_WRONG_GENERIC`. Case-insensitive. Omit for list mode.' },
      source: { type: 'string', description: 'List-mode filter — restrict results to one validator (e.g. `dbx_model_validate`).' },
      severity: { type: 'string', enum: ['error', 'warning'], description: 'List-mode filter — narrow to one severity tier.' },
      format: { type: 'string', enum: ['markdown', 'json'], description: 'Output format. Defaults to markdown.' }
    }
  }
};

async function run(rawArgs: unknown): Promise<ToolResult> {
  const parsed = ExplainRuleArgsType(rawArgs);
  if (parsed instanceof type.errors) {
    return toolError(`Invalid arguments: ${parsed.summary}`);
  }
  if (parsed.code !== undefined) {
    return runLookup({ code: parsed.code, format: parsed.format });
  }
  return runList({ source: parsed.source, severity: parsed.severity, format: parsed.format });
}

interface RunLookupInput {
  readonly code: string;
  readonly format: 'markdown' | 'json' | undefined;
}

function runLookup(input: RunLookupInput): ToolResult {
  const exact = findRule(input.code);
  if (exact) {
    const text = input.format === 'json' ? formatRuleAsJson(exact) : formatRuleAsMarkdown(exact);
    const result: ToolResult = { content: [{ type: 'text', text }] };
    return result;
  }
  const candidates = searchRules(input.code, 5);
  if (candidates.length === 0) {
    return toolError(`No rule found for code \`${input.code}\`. The catalog has ${RULE_CATALOG.length} entries; try \`dbx_explain_rule code="<keyword>"\` to search by substring, or omit \`code\` for a full listing.`);
  }
  const lines: string[] = [`# No exact match for \`${input.code}\``, '', `Top ${candidates.length} candidate${candidates.length === 1 ? '' : 's'}:`, ''];
  for (const candidate of candidates) {
    lines.push(`- \`${candidate.code}\` (${candidate.source}, ${candidate.severity}) — ${candidate.title}`);
  }
  lines.push('', 'Re-run `dbx_explain_rule code="<exact code>"` for the full doc.');
  const text = input.format === 'json' ? JSON.stringify({ candidates }, null, 2) : lines.join('\n');
  const result: ToolResult = { content: [{ type: 'text', text }], isError: true };
  return result;
}

interface RunListInput {
  readonly source: string | undefined;
  readonly severity: RuleSeverity | undefined;
  readonly format: 'markdown' | 'json' | undefined;
}

function applyListFilters(input: RunListInput): readonly RuleEntry[] {
  const filters: ((entry: RuleEntry) => boolean)[] = [];
  if (input.source !== undefined) {
    const wanted = input.source as RuleSource;
    filters.push((entry) => entry.source === wanted);
  }
  if (input.severity !== undefined) {
    filters.push((entry) => entry.severity === input.severity);
  }
  return filters.length === 0 ? RULE_CATALOG : RULE_CATALOG.filter((entry) => filters.every((f) => f(entry)));
}

function describeListFilters(input: RunListInput): readonly string[] {
  const filterParts: string[] = [];
  if (input.source !== undefined) filterParts.push(`source=\`${input.source}\``);
  if (input.severity !== undefined) filterParts.push(`severity=\`${input.severity}\``);
  return filterParts;
}

function renderListMarkdown(filtered: readonly RuleEntry[], filterParts: readonly string[]): string {
  const lines: string[] = [];
  const heading = filterParts.length === 0 ? `Rule catalog (${filtered.length} entries)` : `Rule catalog — ${filterParts.join(', ')} (${filtered.length} of ${RULE_CATALOG.length} entries)`;
  lines.push(`# ${heading}`, '');
  const grouped = groupBySource(filtered);
  for (const [source, entries] of grouped) {
    lines.push(`## \`${source}\` (${entries.length})`, '');
    for (const entry of entries) {
      lines.push(`- \`${entry.code}\` (${entry.severity}) — ${entry.title}`);
    }
    lines.push('');
  }
  lines.push(`Re-run \`dbx_explain_rule code="<code>"\` for the full doc on any rule.`);
  return lines.join('\n').trimEnd();
}

function runList(input: RunListInput): ToolResult {
  const filtered = applyListFilters(input);
  const filterParts = describeListFilters(input);
  if (filtered.length === 0) {
    const filterSummary = filterParts.length === 0 ? '' : ` (filters: ${filterParts.join(', ')})`;
    return toolError(`No rules match${filterSummary}. The catalog has ${RULE_CATALOG.length} entries — try omitting filters to list all rules.`);
  }
  if (input.format === 'json') {
    const text = JSON.stringify({ entries: filtered.map(({ code, source, severity, title }) => ({ code, source, severity, title })) }, null, 2);
    return { content: [{ type: 'text', text }] };
  }
  return { content: [{ type: 'text', text: renderListMarkdown(filtered, filterParts) }] };
}

function groupBySource(entries: readonly RuleEntry[]): readonly (readonly [RuleSource, readonly RuleEntry[]])[] {
  const map = new Map<RuleSource, RuleEntry[]>();
  for (const entry of entries) {
    const bucket = map.get(entry.source);
    if (bucket === undefined) {
      map.set(entry.source, [entry]);
    } else {
      bucket.push(entry);
    }
  }
  return [...map.entries()].sort(([a], [b]) => a.localeCompare(b));
}

export const EXPLAIN_RULE_TOOL: DbxTool = { definition: TOOL, run };
