/**
 * `dbx_explain_rule` tool.
 *
 * Looks up one rule from the generated rule catalog by exact code
 * match and renders its full documentation block — title, severity,
 * source tool, what-it-flags, when-it-applies, when-it-does-NOT-apply,
 * canonical fix, optional fix template, and optional see-also links.
 *
 * Misremembered codes trigger a substring search across the catalog
 * (via `searchRules(...)`) and the result lists the top candidates so
 * the caller can re-issue with the correct code.
 *
 * Pure data — no AST, no file I/O. Backed by the catalog generated by
 * `scripts/extract-rule-catalog.mjs` from the per-cluster `codes.ts`
 * enum members.
 */

import { type Tool } from '@modelcontextprotocol/sdk/types.js';
import { type } from 'arktype';
import { findRule, formatRuleAsJson, formatRuleAsMarkdown, RULE_CATALOG, searchRules } from './rule-catalog/index.js';
import { toolError, type DbxTool, type ToolResult } from './types.js';

const ExplainRuleArgsType = type({
  code: 'string',
  'format?': "'markdown' | 'json'"
});

const TOOL: Tool = {
  name: 'dbx_explain_rule',
  description: [
    'Explain one validation rule by code. Returns the title, severity, source tool, what it flags, when it applies, when it does NOT apply, canonical fix, optional fix template, and any see-also references.',
    '',
    'Use this when:',
    '- A validator emitted a code (e.g. `MODEL_COLLECTION_TYPE_WRONG_GENERIC` or `STORAGEFILE_GROUP_IDS_FUNCTION_MISSING`) and you want to know whether the diagnostic actually applies to your case.',
    '- You need the canonical helper-function template for the fix without round-tripping through `dbx_artifact_file_convention`.',
    '- You misremember a code — pass your best guess; an unknown code returns the top 5 catalog candidates.',
    '',
    'Inputs:',
    '- `code`: the rule code (case-insensitive) to look up.',
    '- `format` (optional): `markdown` (default) or `json`.'
  ].join('\n'),
  inputSchema: {
    type: 'object',
    properties: {
      code: { type: 'string', description: 'The rule code, e.g. `MODEL_COLLECTION_TYPE_WRONG_GENERIC`. Case-insensitive.' },
      format: { type: 'string', enum: ['markdown', 'json'], description: 'Output format. Defaults to markdown.' }
    },
    required: ['code']
  }
};

async function run(rawArgs: unknown): Promise<ToolResult> {
  const parsed = ExplainRuleArgsType(rawArgs);
  if (parsed instanceof type.errors) {
    return toolError(`Invalid arguments: ${parsed.summary}`);
  }
  const exact = findRule(parsed.code);
  if (exact) {
    const text = parsed.format === 'json' ? formatRuleAsJson(exact) : formatRuleAsMarkdown(exact);
    const result: ToolResult = { content: [{ type: 'text', text }] };
    return result;
  }
  const candidates = searchRules(parsed.code, 5);
  if (candidates.length === 0) {
    return toolError(`No rule found for code \`${parsed.code}\`. The catalog has ${RULE_CATALOG.length} entries; try \`dbx_explain_rule code="<keyword>"\` to search by substring.`);
  }
  const lines: string[] = [`# No exact match for \`${parsed.code}\``, '', `Top ${candidates.length} candidate${candidates.length === 1 ? '' : 's'}:`, ''];
  for (const candidate of candidates) {
    lines.push(`- \`${candidate.code}\` (${candidate.source}, ${candidate.severity}) — ${candidate.title}`);
  }
  lines.push('', 'Re-run `dbx_explain_rule code="<exact code>"` for the full doc.');
  const text = parsed.format === 'json' ? JSON.stringify({ candidates }, null, 2) : lines.join('\n');
  const result: ToolResult = { content: [{ type: 'text', text }], isError: true };
  return result;
}

export const explainRuleTool: DbxTool = { definition: TOOL, run };
