import { PromiseOrValue } from '@dereekb/util';
import { INestApplicationContext } from '@nestjs/common';
import * as functions from 'firebase-functions';
import { EventContext } from 'firebase-functions';
import { MakeNestContext, NestApplicationFunctionFactory, NestApplicationPromiseGetter } from '../../nest.provider';

// MARK: Event
export type FirestoreEventHandler<I = unknown, O = unknown> = (data: I, context: EventContext) => PromiseOrValue<O>;
export type NestApplicationEventHandler<I = unknown, O = unknown> = (nest: INestApplicationContext, data: I, context: EventContext) => PromiseOrValue<O>;
export type NestApplicationEventHandlerBuilder<I = unknown, O = unknown> = (handler: NestApplicationEventHandler<I, O>) => FirestoreEventHandler<I, O>;

export type OnEventWithNestApplicationBuilder<I = unknown, O = unknown> = (nest: NestApplicationEventHandlerBuilder<I, O>) => functions.CloudFunction<I>;

/**
 * Factory function for generating a CloudFunctionHandler via a NestApplicationCloudFunctionHandler.
 */
export type OnEventWithNestApplicationFactory = <I, O>(fn: OnEventWithNestApplicationBuilder<I, O>) => NestApplicationFunctionFactory<functions.CloudFunction<I>>;

/**
 * Creates a factory for generating OnEventWithNestApplicationBuilder values.
 *
 * @param nestAppPromiseGetter
 * @returns
 */
export function onEventWithNestApplicationFactory(): OnEventWithNestApplicationFactory {
  return <I, O>(fn: OnEventWithNestApplicationBuilder<I, O>) => {
    return (nestAppPromiseGetter: NestApplicationPromiseGetter) => {
      const handlerBuilder: NestApplicationEventHandlerBuilder<I, O> = (handler) => {
        const fnHandler: FirestoreEventHandler<I, O> = (data, context) => nestAppPromiseGetter().then((nest) => handler(nest, data, context));
        return fnHandler;
      };

      return fn(handlerBuilder);
    };
  };
}

export type NestContextEventHandler<C, I = unknown, O = unknown> = (nest: C, data: I, context: EventContext) => Promise<O>;
export type NestContextEventHandlerBuilder<C, I = unknown, O = unknown> = (handler: NestContextEventHandler<C, I, O>) => FirestoreEventHandler<I, O>;

/**
 * Runnable function that is passed an arbitrary nest context object in addition to the usual data/context provided by firebase.
 */
export type OnEventWithNestContextBuilder<C, I = unknown, O = unknown> = (nest: NestContextEventHandlerBuilder<C, I, O>) => functions.CloudFunction<I>;

/**
 * Factory function for generating a firebase CloudFunction for a specific event.
 */
export type OnEventWithNestContextFactory<C> = <I, O = unknown>(fn: OnEventWithNestContextBuilder<C, I, O>) => NestApplicationFunctionFactory<functions.CloudFunction<I>>;

/**
 * Creates a factory for generating OnCallWithNestContext functions with a nest context object that is generated by the input function.
 *
 * @param appFactory
 * @param makeNestContext
 * @returns
 */
export function onEventWithNestContextFactory<C>(makeNestContext: MakeNestContext<C>): OnEventWithNestContextFactory<C> {
  return <I, O = unknown>(fn: OnEventWithNestContextBuilder<C, I, O>) => {
    return (nestAppPromiseGetter: NestApplicationPromiseGetter) => {
      const handlerBuilder: NestContextEventHandlerBuilder<C, I, O> = (handler) => {
        const fnHandler: FirestoreEventHandler<I, O> = (data, context) => nestAppPromiseGetter().then((nest) => handler(makeNestContext(nest), data, context));
        return fnHandler;
      };

      return fn(handlerBuilder);
    };
  };
}
